import { assertEquals } from "@std/assert";
import SimpleDB from "../../../src/class/SimpleDB.ts";

Deno.test("should clone a column with an offset", async () => {
  const sdb = new SimpleDB();
  const table = sdb.newTable("data");
  await table.loadArray([
    { firstName: "nael", lastName: "shiab" },
    { firstName: "graeme", lastName: "bruce" },
    { firstName: "wendy", lastName: "martinez" },
    { firstName: "andrew", lastName: "ryan" },
  ]);

  await table.cloneColumnWithOffset("firstName", "nextFirstName");

  const data = await table.getData();

  assertEquals(data, [
    { firstName: "nael", lastName: "shiab", nextFirstName: "graeme" },
    { firstName: "graeme", lastName: "bruce", nextFirstName: "wendy" },
    {
      firstName: "wendy",
      lastName: "martinez",
      nextFirstName: "andrew",
    },
    { firstName: "andrew", lastName: "ryan", nextFirstName: null },
  ]);

  await sdb.done();
});
Deno.test("should clone a column with an offset of 2", async () => {
  const sdb = new SimpleDB();
  const table = sdb.newTable("data");
  await table.loadArray([
    { firstName: "nael", lastName: "shiab" },
    { firstName: "graeme", lastName: "bruce" },
    { firstName: "wendy", lastName: "martinez" },
    { firstName: "andrew", lastName: "ryan" },
  ]);

  await table.cloneColumnWithOffset("firstName", "nextFirstName", {
    offset: 2,
  });

  const data = await table.getData();

  assertEquals(data, [
    { firstName: "nael", lastName: "shiab", nextFirstName: "wendy" },
    { firstName: "graeme", lastName: "bruce", nextFirstName: "andrew" },
    {
      firstName: "wendy",
      lastName: "martinez",
      nextFirstName: null,
    },
    { firstName: "andrew", lastName: "ryan", nextFirstName: null },
  ]);

  await sdb.done();
});
Deno.test("should clone a column with a category", async () => {
  const sdb = new SimpleDB();
  const table = sdb.newTable("data");
  await table.loadArray([
    { group: "A", firstName: "nael", lastName: "shiab" },
    { group: "B", firstName: "wendy", lastName: "martinez" },
    { group: "A", firstName: "graeme", lastName: "bruce" },
    { group: "B", firstName: "andrew", lastName: "ryan" },
  ]);

  await table.cloneColumnWithOffset("firstName", "nextFirstName", {
    categories: "group",
  });

  const data = await table.getData();

  assertEquals(data, [
    {
      group: "A",
      firstName: "nael",
      lastName: "shiab",
      nextFirstName: "graeme",
    },
    {
      group: "A",
      firstName: "graeme",
      lastName: "bruce",
      nextFirstName: null,
    },
    {
      group: "B",
      firstName: "wendy",
      lastName: "martinez",
      nextFirstName: "andrew",
    },
    {
      group: "B",
      firstName: "andrew",
      lastName: "ryan",
      nextFirstName: null,
    },
  ]);

  await sdb.done();
});
Deno.test("should clone a column with an offset when working with geometries and keep the projection", async () => {
  const sdb = new SimpleDB();
  const table = sdb.newTable("data");
  await table.loadGeoData(
    "test/geodata/files/CanadianProvincesAndTerritories.json",
  );

  await table.cloneColumnWithOffset("geom", "geomClone");

  assertEquals(
    table.projections["geom"],
    table.projections["geomClone"],
  );

  await sdb.done();
});
Deno.test("should clone a column with a positive offset when working with many rows", async () => {
  const sdb = new SimpleDB();
  const table = sdb.newTable("data");
  await table.loadData("test/data/files/rents.csv");
  await table.cloneColumnWithOffset("rent", "previousYearRent", {
    offset: -1,
    categories: "bedroomType",
  });

  const data = await table.getData();
  assertEquals(
    data,
    [{
      "year": 1998,
      "bedroomType": "oneBedroom",
      "rent": 438,
      "previousYearRent": null,
    }, {
      "year": 1999,
      "bedroomType": "oneBedroom",
      "rent": 452,
      "previousYearRent": 438,
    }, {
      "year": 2000,
      "bedroomType": "oneBedroom",
      "rent": 458,
      "previousYearRent": 452,
    }, {
      "year": 2001,
      "bedroomType": "oneBedroom",
      "rent": 476,
      "previousYearRent": 458,
    }, {
      "year": 2002,
      "bedroomType": "oneBedroom",
      "rent": 505,
      "previousYearRent": 476,
    }, {
      "year": 2003,
      "bedroomType": "oneBedroom",
      "rent": 528,
      "previousYearRent": 505,
    }, {
      "year": 2004,
      "bedroomType": "oneBedroom",
      "rent": 539,
      "previousYearRent": 528,
    }, {
      "year": 2005,
      "bedroomType": "oneBedroom",
      "rent": 562,
      "previousYearRent": 539,
    }, {
      "year": 2006,
      "bedroomType": "oneBedroom",
      "rent": 574,
      "previousYearRent": 562,
    }, {
      "year": 2007,
      "bedroomType": "oneBedroom",
      "rent": 581,
      "previousYearRent": 574,
    }, {
      "year": 2008,
      "bedroomType": "oneBedroom",
      "rent": 594,
      "previousYearRent": 581,
    }, {
      "year": 2009,
      "bedroomType": "oneBedroom",
      "rent": 604,
      "previousYearRent": 594,
    }, {
      "year": 2010,
      "bedroomType": "oneBedroom",
      "rent": 627,
      "previousYearRent": 604,
    }, {
      "year": 2011,
      "bedroomType": "oneBedroom",
      "rent": 641,
      "previousYearRent": 627,
    }, {
      "year": 2012,
      "bedroomType": "oneBedroom",
      "rent": 637,
      "previousYearRent": 641,
    }, {
      "year": 2013,
      "bedroomType": "oneBedroom",
      "rent": 651,
      "previousYearRent": 637,
    }, {
      "year": 2014,
      "bedroomType": "oneBedroom",
      "rent": 655,
      "previousYearRent": 651,
    }, {
      "year": 2015,
      "bedroomType": "oneBedroom",
      "rent": 668,
      "previousYearRent": 655,
    }, {
      "year": 2016,
      "bedroomType": "oneBedroom",
      "rent": 679,
      "previousYearRent": 668,
    }, {
      "year": 2017,
      "bedroomType": "oneBedroom",
      "rent": 698,
      "previousYearRent": 679,
    }, {
      "year": 2018,
      "bedroomType": "oneBedroom",
      "rent": 720,
      "previousYearRent": 698,
    }, {
      "year": 2019,
      "bedroomType": "oneBedroom",
      "rent": 754,
      "previousYearRent": 720,
    }, {
      "year": 2020,
      "bedroomType": "oneBedroom",
      "rent": 810,
      "previousYearRent": 754,
    }, {
      "year": 2021,
      "bedroomType": "oneBedroom",
      "rent": 821,
      "previousYearRent": 810,
    }, {
      "year": 2022,
      "bedroomType": "oneBedroom",
      "rent": 912,
      "previousYearRent": 821,
    }, {
      "year": 2023,
      "bedroomType": "oneBedroom",
      "rent": 960,
      "previousYearRent": 912,
    }, {
      "year": 2024,
      "bedroomType": "oneBedroom",
      "rent": 1051,
      "previousYearRent": 960,
    }, {
      "year": 2025,
      "bedroomType": "oneBedroom",
      "rent": 1131,
      "previousYearRent": 1051,
    }, {
      "year": 1998,
      "bedroomType": "studio",
      "rent": 365,
      "previousYearRent": null,
    }, {
      "year": 1999,
      "bedroomType": "studio",
      "rent": 372,
      "previousYearRent": 365,
    }, {
      "year": 2000,
      "bedroomType": "studio",
      "rent": 380,
      "previousYearRent": 372,
    }, {
      "year": 2001,
      "bedroomType": "studio",
      "rent": 404,
      "previousYearRent": 380,
    }, {
      "year": 2002,
      "bedroomType": "studio",
      "rent": 423,
      "previousYearRent": 404,
    }, {
      "year": 2003,
      "bedroomType": "studio",
      "rent": 441,
      "previousYearRent": 423,
    }, {
      "year": 2004,
      "bedroomType": "studio",
      "rent": 459,
      "previousYearRent": 441,
    }, {
      "year": 2005,
      "bedroomType": "studio",
      "rent": 466,
      "previousYearRent": 459,
    }, {
      "year": 2006,
      "bedroomType": "studio",
      "rent": 481,
      "previousYearRent": 466,
    }, {
      "year": 2007,
      "bedroomType": "studio",
      "rent": 490,
      "previousYearRent": 481,
    }, {
      "year": 2008,
      "bedroomType": "studio",
      "rent": 500,
      "previousYearRent": 490,
    }, {
      "year": 2009,
      "bedroomType": "studio",
      "rent": 514,
      "previousYearRent": 500,
    }, {
      "year": 2010,
      "bedroomType": "studio",
      "rent": 526,
      "previousYearRent": 514,
    }, {
      "year": 2011,
      "bedroomType": "studio",
      "rent": 549,
      "previousYearRent": 526,
    }, {
      "year": 2012,
      "bedroomType": "studio",
      "rent": 539,
      "previousYearRent": 549,
    }, {
      "year": 2013,
      "bedroomType": "studio",
      "rent": 555,
      "previousYearRent": 539,
    }, {
      "year": 2014,
      "bedroomType": "studio",
      "rent": 569,
      "previousYearRent": 555,
    }, {
      "year": 2015,
      "bedroomType": "studio",
      "rent": 573,
      "previousYearRent": 569,
    }, {
      "year": 2016,
      "bedroomType": "studio",
      "rent": 586,
      "previousYearRent": 573,
    }, {
      "year": 2017,
      "bedroomType": "studio",
      "rent": 598,
      "previousYearRent": 586,
    }, {
      "year": 2018,
      "bedroomType": "studio",
      "rent": 641,
      "previousYearRent": 598,
    }, {
      "year": 2019,
      "bedroomType": "studio",
      "rent": 655,
      "previousYearRent": 641,
    }, {
      "year": 2020,
      "bedroomType": "studio",
      "rent": 702,
      "previousYearRent": 655,
    }, {
      "year": 2021,
      "bedroomType": "studio",
      "rent": 712,
      "previousYearRent": 702,
    }, {
      "year": 2022,
      "bedroomType": "studio",
      "rent": 785,
      "previousYearRent": 712,
    }, {
      "year": 2023,
      "bedroomType": "studio",
      "rent": 810,
      "previousYearRent": 785,
    }, {
      "year": 2024,
      "bedroomType": "studio",
      "rent": 892,
      "previousYearRent": 810,
    }, {
      "year": 2025,
      "bedroomType": "studio",
      "rent": 1005,
      "previousYearRent": 892,
    }, {
      "year": 1998,
      "bedroomType": "threeBedroomPlus",
      "rent": 597,
      "previousYearRent": null,
    }, {
      "year": 1999,
      "bedroomType": "threeBedroomPlus",
      "rent": 614,
      "previousYearRent": 597,
    }, {
      "year": 2000,
      "bedroomType": "threeBedroomPlus",
      "rent": 631,
      "previousYearRent": 614,
    }, {
      "year": 2001,
      "bedroomType": "threeBedroomPlus",
      "rent": 652,
      "previousYearRent": 631,
    }, {
      "year": 2002,
      "bedroomType": "threeBedroomPlus",
      "rent": 688,
      "previousYearRent": 652,
    }, {
      "year": 2003,
      "bedroomType": "threeBedroomPlus",
      "rent": 713,
      "previousYearRent": 688,
    }, {
      "year": 2004,
      "bedroomType": "threeBedroomPlus",
      "rent": 729,
      "previousYearRent": 713,
    }, {
      "year": 2005,
      "bedroomType": "threeBedroomPlus",
      "rent": 744,
      "previousYearRent": 729,
    }, {
      "year": 2006,
      "bedroomType": "threeBedroomPlus",
      "rent": 777,
      "previousYearRent": 744,
    }, {
      "year": 2007,
      "bedroomType": "threeBedroomPlus",
      "rent": 808,
      "previousYearRent": 777,
    }, {
      "year": 2008,
      "bedroomType": "threeBedroomPlus",
      "rent": 801,
      "previousYearRent": 808,
    }, {
      "year": 2009,
      "bedroomType": "threeBedroomPlus",
      "rent": 815,
      "previousYearRent": 801,
    }, {
      "year": 2010,
      "bedroomType": "threeBedroomPlus",
      "rent": 863,
      "previousYearRent": 815,
    }, {
      "year": 2011,
      "bedroomType": "threeBedroomPlus",
      "rent": 868,
      "previousYearRent": 863,
    }, {
      "year": 2012,
      "bedroomType": "threeBedroomPlus",
      "rent": 876,
      "previousYearRent": 868,
    }, {
      "year": 2013,
      "bedroomType": "threeBedroomPlus",
      "rent": 879,
      "previousYearRent": 876,
    }, {
      "year": 2014,
      "bedroomType": "threeBedroomPlus",
      "rent": 898,
      "previousYearRent": 879,
    }, {
      "year": 2015,
      "bedroomType": "threeBedroomPlus",
      "rent": 953,
      "previousYearRent": 898,
    }, {
      "year": 2016,
      "bedroomType": "threeBedroomPlus",
      "rent": 958,
      "previousYearRent": 953,
    }, {
      "year": 2017,
      "bedroomType": "threeBedroomPlus",
      "rent": 966,
      "previousYearRent": 958,
    }, {
      "year": 2018,
      "bedroomType": "threeBedroomPlus",
      "rent": 1009,
      "previousYearRent": 966,
    }, {
      "year": 2019,
      "bedroomType": "threeBedroomPlus",
      "rent": 1072,
      "previousYearRent": 1009,
    }, {
      "year": 2020,
      "bedroomType": "threeBedroomPlus",
      "rent": 1113,
      "previousYearRent": 1072,
    }, {
      "year": 2021,
      "bedroomType": "threeBedroomPlus",
      "rent": 1146,
      "previousYearRent": 1113,
    }, {
      "year": 2022,
      "bedroomType": "threeBedroomPlus",
      "rent": 1232,
      "previousYearRent": 1146,
    }, {
      "year": 2023,
      "bedroomType": "threeBedroomPlus",
      "rent": 1324,
      "previousYearRent": 1232,
    }, {
      "year": 2024,
      "bedroomType": "threeBedroomPlus",
      "rent": 1489,
      "previousYearRent": 1324,
    }, {
      "year": 2025,
      "bedroomType": "threeBedroomPlus",
      "rent": 1625,
      "previousYearRent": 1489,
    }, {
      "year": 1998,
      "bedroomType": "twoBedroom",
      "rent": 499,
      "previousYearRent": null,
    }, {
      "year": 1999,
      "bedroomType": "twoBedroom",
      "rent": 506,
      "previousYearRent": 499,
    }, {
      "year": 2000,
      "bedroomType": "twoBedroom",
      "rent": 509,
      "previousYearRent": 506,
    }, {
      "year": 2001,
      "bedroomType": "twoBedroom",
      "rent": 529,
      "previousYearRent": 509,
    }, {
      "year": 2002,
      "bedroomType": "twoBedroom",
      "rent": 552,
      "previousYearRent": 529,
    }, {
      "year": 2003,
      "bedroomType": "twoBedroom",
      "rent": 575,
      "previousYearRent": 552,
    }, {
      "year": 2004,
      "bedroomType": "twoBedroom",
      "rent": 594,
      "previousYearRent": 575,
    }, {
      "year": 2005,
      "bedroomType": "twoBedroom",
      "rent": 616,
      "previousYearRent": 594,
    }, {
      "year": 2006,
      "bedroomType": "twoBedroom",
      "rent": 636,
      "previousYearRent": 616,
    }, {
      "year": 2007,
      "bedroomType": "twoBedroom",
      "rent": 647,
      "previousYearRent": 636,
    }, {
      "year": 2008,
      "bedroomType": "twoBedroom",
      "rent": 659,
      "previousYearRent": 647,
    }, {
      "year": 2009,
      "bedroomType": "twoBedroom",
      "rent": 669,
      "previousYearRent": 659,
    }, {
      "year": 2010,
      "bedroomType": "twoBedroom",
      "rent": 701,
      "previousYearRent": 669,
    }, {
      "year": 2011,
      "bedroomType": "twoBedroom",
      "rent": 719,
      "previousYearRent": 701,
    }, {
      "year": 2012,
      "bedroomType": "twoBedroom",
      "rent": 711,
      "previousYearRent": 719,
    }, {
      "year": 2013,
      "bedroomType": "twoBedroom",
      "rent": 730,
      "previousYearRent": 711,
    }, {
      "year": 2014,
      "bedroomType": "twoBedroom",
      "rent": 739,
      "previousYearRent": 730,
    }, {
      "year": 2015,
      "bedroomType": "twoBedroom",
      "rent": 760,
      "previousYearRent": 739,
    }, {
      "year": 2016,
      "bedroomType": "twoBedroom",
      "rent": 791,
      "previousYearRent": 760,
    }, {
      "year": 2017,
      "bedroomType": "twoBedroom",
      "rent": 782,
      "previousYearRent": 791,
    }, {
      "year": 2018,
      "bedroomType": "twoBedroom",
      "rent": 809,
      "previousYearRent": 782,
    }, {
      "year": 2019,
      "bedroomType": "twoBedroom",
      "rent": 856,
      "previousYearRent": 809,
    }, {
      "year": 2020,
      "bedroomType": "twoBedroom",
      "rent": 903,
      "previousYearRent": 856,
    }, {
      "year": 2021,
      "bedroomType": "twoBedroom",
      "rent": 932,
      "previousYearRent": 903,
    }, {
      "year": 2022,
      "bedroomType": "twoBedroom",
      "rent": 1022,
      "previousYearRent": 932,
    }, {
      "year": 2023,
      "bedroomType": "twoBedroom",
      "rent": 1096,
      "previousYearRent": 1022,
    }, {
      "year": 2024,
      "bedroomType": "twoBedroom",
      "rent": 1176,
      "previousYearRent": 1096,
    }, {
      "year": 2025,
      "bedroomType": "twoBedroom",
      "rent": 1346,
      "previousYearRent": 1176,
    }] as {
      [key: string]: string | number | boolean | Date | null;
    }[],
  );
});
Deno.test("should clone a column with a negative offset when working with many rows", async () => {
  const sdb = new SimpleDB();
  const table = sdb.newTable("data");
  await table.loadData("test/data/files/rents.csv");
  await table.cloneColumnWithOffset("rent", "nextYearRent", {
    offset: 1,
    categories: "bedroomType",
  });

  const data = await table.getData();
  assertEquals(
    data,
    [{
      "year": 1998,
      "bedroomType": "oneBedroom",
      "rent": 438,
      "nextYearRent": 452,
    }, {
      "year": 1999,
      "bedroomType": "oneBedroom",
      "rent": 452,
      "nextYearRent": 458,
    }, {
      "year": 2000,
      "bedroomType": "oneBedroom",
      "rent": 458,
      "nextYearRent": 476,
    }, {
      "year": 2001,
      "bedroomType": "oneBedroom",
      "rent": 476,
      "nextYearRent": 505,
    }, {
      "year": 2002,
      "bedroomType": "oneBedroom",
      "rent": 505,
      "nextYearRent": 528,
    }, {
      "year": 2003,
      "bedroomType": "oneBedroom",
      "rent": 528,
      "nextYearRent": 539,
    }, {
      "year": 2004,
      "bedroomType": "oneBedroom",
      "rent": 539,
      "nextYearRent": 562,
    }, {
      "year": 2005,
      "bedroomType": "oneBedroom",
      "rent": 562,
      "nextYearRent": 574,
    }, {
      "year": 2006,
      "bedroomType": "oneBedroom",
      "rent": 574,
      "nextYearRent": 581,
    }, {
      "year": 2007,
      "bedroomType": "oneBedroom",
      "rent": 581,
      "nextYearRent": 594,
    }, {
      "year": 2008,
      "bedroomType": "oneBedroom",
      "rent": 594,
      "nextYearRent": 604,
    }, {
      "year": 2009,
      "bedroomType": "oneBedroom",
      "rent": 604,
      "nextYearRent": 627,
    }, {
      "year": 2010,
      "bedroomType": "oneBedroom",
      "rent": 627,
      "nextYearRent": 641,
    }, {
      "year": 2011,
      "bedroomType": "oneBedroom",
      "rent": 641,
      "nextYearRent": 637,
    }, {
      "year": 2012,
      "bedroomType": "oneBedroom",
      "rent": 637,
      "nextYearRent": 651,
    }, {
      "year": 2013,
      "bedroomType": "oneBedroom",
      "rent": 651,
      "nextYearRent": 655,
    }, {
      "year": 2014,
      "bedroomType": "oneBedroom",
      "rent": 655,
      "nextYearRent": 668,
    }, {
      "year": 2015,
      "bedroomType": "oneBedroom",
      "rent": 668,
      "nextYearRent": 679,
    }, {
      "year": 2016,
      "bedroomType": "oneBedroom",
      "rent": 679,
      "nextYearRent": 698,
    }, {
      "year": 2017,
      "bedroomType": "oneBedroom",
      "rent": 698,
      "nextYearRent": 720,
    }, {
      "year": 2018,
      "bedroomType": "oneBedroom",
      "rent": 720,
      "nextYearRent": 754,
    }, {
      "year": 2019,
      "bedroomType": "oneBedroom",
      "rent": 754,
      "nextYearRent": 810,
    }, {
      "year": 2020,
      "bedroomType": "oneBedroom",
      "rent": 810,
      "nextYearRent": 821,
    }, {
      "year": 2021,
      "bedroomType": "oneBedroom",
      "rent": 821,
      "nextYearRent": 912,
    }, {
      "year": 2022,
      "bedroomType": "oneBedroom",
      "rent": 912,
      "nextYearRent": 960,
    }, {
      "year": 2023,
      "bedroomType": "oneBedroom",
      "rent": 960,
      "nextYearRent": 1051,
    }, {
      "year": 2024,
      "bedroomType": "oneBedroom",
      "rent": 1051,
      "nextYearRent": 1131,
    }, {
      "year": 2025,
      "bedroomType": "oneBedroom",
      "rent": 1131,
      "nextYearRent": null,
    }, {
      "year": 1998,
      "bedroomType": "studio",
      "rent": 365,
      "nextYearRent": 372,
    }, {
      "year": 1999,
      "bedroomType": "studio",
      "rent": 372,
      "nextYearRent": 380,
    }, {
      "year": 2000,
      "bedroomType": "studio",
      "rent": 380,
      "nextYearRent": 404,
    }, {
      "year": 2001,
      "bedroomType": "studio",
      "rent": 404,
      "nextYearRent": 423,
    }, {
      "year": 2002,
      "bedroomType": "studio",
      "rent": 423,
      "nextYearRent": 441,
    }, {
      "year": 2003,
      "bedroomType": "studio",
      "rent": 441,
      "nextYearRent": 459,
    }, {
      "year": 2004,
      "bedroomType": "studio",
      "rent": 459,
      "nextYearRent": 466,
    }, {
      "year": 2005,
      "bedroomType": "studio",
      "rent": 466,
      "nextYearRent": 481,
    }, {
      "year": 2006,
      "bedroomType": "studio",
      "rent": 481,
      "nextYearRent": 490,
    }, {
      "year": 2007,
      "bedroomType": "studio",
      "rent": 490,
      "nextYearRent": 500,
    }, {
      "year": 2008,
      "bedroomType": "studio",
      "rent": 500,
      "nextYearRent": 514,
    }, {
      "year": 2009,
      "bedroomType": "studio",
      "rent": 514,
      "nextYearRent": 526,
    }, {
      "year": 2010,
      "bedroomType": "studio",
      "rent": 526,
      "nextYearRent": 549,
    }, {
      "year": 2011,
      "bedroomType": "studio",
      "rent": 549,
      "nextYearRent": 539,
    }, {
      "year": 2012,
      "bedroomType": "studio",
      "rent": 539,
      "nextYearRent": 555,
    }, {
      "year": 2013,
      "bedroomType": "studio",
      "rent": 555,
      "nextYearRent": 569,
    }, {
      "year": 2014,
      "bedroomType": "studio",
      "rent": 569,
      "nextYearRent": 573,
    }, {
      "year": 2015,
      "bedroomType": "studio",
      "rent": 573,
      "nextYearRent": 586,
    }, {
      "year": 2016,
      "bedroomType": "studio",
      "rent": 586,
      "nextYearRent": 598,
    }, {
      "year": 2017,
      "bedroomType": "studio",
      "rent": 598,
      "nextYearRent": 641,
    }, {
      "year": 2018,
      "bedroomType": "studio",
      "rent": 641,
      "nextYearRent": 655,
    }, {
      "year": 2019,
      "bedroomType": "studio",
      "rent": 655,
      "nextYearRent": 702,
    }, {
      "year": 2020,
      "bedroomType": "studio",
      "rent": 702,
      "nextYearRent": 712,
    }, {
      "year": 2021,
      "bedroomType": "studio",
      "rent": 712,
      "nextYearRent": 785,
    }, {
      "year": 2022,
      "bedroomType": "studio",
      "rent": 785,
      "nextYearRent": 810,
    }, {
      "year": 2023,
      "bedroomType": "studio",
      "rent": 810,
      "nextYearRent": 892,
    }, {
      "year": 2024,
      "bedroomType": "studio",
      "rent": 892,
      "nextYearRent": 1005,
    }, {
      "year": 2025,
      "bedroomType": "studio",
      "rent": 1005,
      "nextYearRent": null,
    }, {
      "year": 1998,
      "bedroomType": "threeBedroomPlus",
      "rent": 597,
      "nextYearRent": 614,
    }, {
      "year": 1999,
      "bedroomType": "threeBedroomPlus",
      "rent": 614,
      "nextYearRent": 631,
    }, {
      "year": 2000,
      "bedroomType": "threeBedroomPlus",
      "rent": 631,
      "nextYearRent": 652,
    }, {
      "year": 2001,
      "bedroomType": "threeBedroomPlus",
      "rent": 652,
      "nextYearRent": 688,
    }, {
      "year": 2002,
      "bedroomType": "threeBedroomPlus",
      "rent": 688,
      "nextYearRent": 713,
    }, {
      "year": 2003,
      "bedroomType": "threeBedroomPlus",
      "rent": 713,
      "nextYearRent": 729,
    }, {
      "year": 2004,
      "bedroomType": "threeBedroomPlus",
      "rent": 729,
      "nextYearRent": 744,
    }, {
      "year": 2005,
      "bedroomType": "threeBedroomPlus",
      "rent": 744,
      "nextYearRent": 777,
    }, {
      "year": 2006,
      "bedroomType": "threeBedroomPlus",
      "rent": 777,
      "nextYearRent": 808,
    }, {
      "year": 2007,
      "bedroomType": "threeBedroomPlus",
      "rent": 808,
      "nextYearRent": 801,
    }, {
      "year": 2008,
      "bedroomType": "threeBedroomPlus",
      "rent": 801,
      "nextYearRent": 815,
    }, {
      "year": 2009,
      "bedroomType": "threeBedroomPlus",
      "rent": 815,
      "nextYearRent": 863,
    }, {
      "year": 2010,
      "bedroomType": "threeBedroomPlus",
      "rent": 863,
      "nextYearRent": 868,
    }, {
      "year": 2011,
      "bedroomType": "threeBedroomPlus",
      "rent": 868,
      "nextYearRent": 876,
    }, {
      "year": 2012,
      "bedroomType": "threeBedroomPlus",
      "rent": 876,
      "nextYearRent": 879,
    }, {
      "year": 2013,
      "bedroomType": "threeBedroomPlus",
      "rent": 879,
      "nextYearRent": 898,
    }, {
      "year": 2014,
      "bedroomType": "threeBedroomPlus",
      "rent": 898,
      "nextYearRent": 953,
    }, {
      "year": 2015,
      "bedroomType": "threeBedroomPlus",
      "rent": 953,
      "nextYearRent": 958,
    }, {
      "year": 2016,
      "bedroomType": "threeBedroomPlus",
      "rent": 958,
      "nextYearRent": 966,
    }, {
      "year": 2017,
      "bedroomType": "threeBedroomPlus",
      "rent": 966,
      "nextYearRent": 1009,
    }, {
      "year": 2018,
      "bedroomType": "threeBedroomPlus",
      "rent": 1009,
      "nextYearRent": 1072,
    }, {
      "year": 2019,
      "bedroomType": "threeBedroomPlus",
      "rent": 1072,
      "nextYearRent": 1113,
    }, {
      "year": 2020,
      "bedroomType": "threeBedroomPlus",
      "rent": 1113,
      "nextYearRent": 1146,
    }, {
      "year": 2021,
      "bedroomType": "threeBedroomPlus",
      "rent": 1146,
      "nextYearRent": 1232,
    }, {
      "year": 2022,
      "bedroomType": "threeBedroomPlus",
      "rent": 1232,
      "nextYearRent": 1324,
    }, {
      "year": 2023,
      "bedroomType": "threeBedroomPlus",
      "rent": 1324,
      "nextYearRent": 1489,
    }, {
      "year": 2024,
      "bedroomType": "threeBedroomPlus",
      "rent": 1489,
      "nextYearRent": 1625,
    }, {
      "year": 2025,
      "bedroomType": "threeBedroomPlus",
      "rent": 1625,
      "nextYearRent": null,
    }, {
      "year": 1998,
      "bedroomType": "twoBedroom",
      "rent": 499,
      "nextYearRent": 506,
    }, {
      "year": 1999,
      "bedroomType": "twoBedroom",
      "rent": 506,
      "nextYearRent": 509,
    }, {
      "year": 2000,
      "bedroomType": "twoBedroom",
      "rent": 509,
      "nextYearRent": 529,
    }, {
      "year": 2001,
      "bedroomType": "twoBedroom",
      "rent": 529,
      "nextYearRent": 552,
    }, {
      "year": 2002,
      "bedroomType": "twoBedroom",
      "rent": 552,
      "nextYearRent": 575,
    }, {
      "year": 2003,
      "bedroomType": "twoBedroom",
      "rent": 575,
      "nextYearRent": 594,
    }, {
      "year": 2004,
      "bedroomType": "twoBedroom",
      "rent": 594,
      "nextYearRent": 616,
    }, {
      "year": 2005,
      "bedroomType": "twoBedroom",
      "rent": 616,
      "nextYearRent": 636,
    }, {
      "year": 2006,
      "bedroomType": "twoBedroom",
      "rent": 636,
      "nextYearRent": 647,
    }, {
      "year": 2007,
      "bedroomType": "twoBedroom",
      "rent": 647,
      "nextYearRent": 659,
    }, {
      "year": 2008,
      "bedroomType": "twoBedroom",
      "rent": 659,
      "nextYearRent": 669,
    }, {
      "year": 2009,
      "bedroomType": "twoBedroom",
      "rent": 669,
      "nextYearRent": 701,
    }, {
      "year": 2010,
      "bedroomType": "twoBedroom",
      "rent": 701,
      "nextYearRent": 719,
    }, {
      "year": 2011,
      "bedroomType": "twoBedroom",
      "rent": 719,
      "nextYearRent": 711,
    }, {
      "year": 2012,
      "bedroomType": "twoBedroom",
      "rent": 711,
      "nextYearRent": 730,
    }, {
      "year": 2013,
      "bedroomType": "twoBedroom",
      "rent": 730,
      "nextYearRent": 739,
    }, {
      "year": 2014,
      "bedroomType": "twoBedroom",
      "rent": 739,
      "nextYearRent": 760,
    }, {
      "year": 2015,
      "bedroomType": "twoBedroom",
      "rent": 760,
      "nextYearRent": 791,
    }, {
      "year": 2016,
      "bedroomType": "twoBedroom",
      "rent": 791,
      "nextYearRent": 782,
    }, {
      "year": 2017,
      "bedroomType": "twoBedroom",
      "rent": 782,
      "nextYearRent": 809,
    }, {
      "year": 2018,
      "bedroomType": "twoBedroom",
      "rent": 809,
      "nextYearRent": 856,
    }, {
      "year": 2019,
      "bedroomType": "twoBedroom",
      "rent": 856,
      "nextYearRent": 903,
    }, {
      "year": 2020,
      "bedroomType": "twoBedroom",
      "rent": 903,
      "nextYearRent": 932,
    }, {
      "year": 2021,
      "bedroomType": "twoBedroom",
      "rent": 932,
      "nextYearRent": 1022,
    }, {
      "year": 2022,
      "bedroomType": "twoBedroom",
      "rent": 1022,
      "nextYearRent": 1096,
    }, {
      "year": 2023,
      "bedroomType": "twoBedroom",
      "rent": 1096,
      "nextYearRent": 1176,
    }, {
      "year": 2024,
      "bedroomType": "twoBedroom",
      "rent": 1176,
      "nextYearRent": 1346,
    }, {
      "year": 2025,
      "bedroomType": "twoBedroom",
      "rent": 1346,
      "nextYearRent": null,
    }] as {
      [key: string]: string | number | boolean | Date | null;
    }[],
  );
});
