import { assertEquals } from "jsr:@std/assert";
import SimpleDB from "../../../src/class/SimpleDB.ts";

Deno.test("should concatenate multiple columns in a new one", async () => {
  const sdb = new SimpleDB();
  const table = sdb.newTable("employees");
  await table.loadData(["test/data/files/employees.json"]);
  await table.concatenate(["Name", "Job"], "concatenated");
  const data = await table.getData();
  assertEquals(data, [
    {
      Name: "OConnell, Donald",
      "Hire date": "21-JUN-07",
      Job: "Clerk",
      Salary: "2600",
      "Department or unit": "50",
      "End-of_year-BONUS?": "1,94%",
      concatenated: "OConnell, DonaldClerk",
    },
    {
      Name: "OConnell, Donald",
      "Hire date": "21-JUN-07",
      Job: "Clerk",
      Salary: "2600",
      "Department or unit": "50",
      "End-of_year-BONUS?": "1,94%",
      concatenated: "OConnell, DonaldClerk",
    },
    {
      Name: "Grant, Douglas",
      "Hire date": "13-JAN-08",
      Job: "Clerk",
      Salary: null,
      "Department or unit": "50",
      "End-of_year-BONUS?": "23,39%",
      concatenated: "Grant, DouglasClerk",
    },
    {
      Name: null,
      "Hire date": "17-SEP-03",
      Job: "Assistant",
      Salary: "4400",
      "Department or unit": "10",
      "End-of_year-BONUS?": "17,51%",
      concatenated: "Assistant",
    },
    {
      Name: "Hartstein, Michael",
      "Hire date": "17-FEB-04",
      Job: "Manager",
      Salary: "13000",
      "Department or unit": "20",
      "End-of_year-BONUS?": "2,71%",
      concatenated: "Hartstein, MichaelManager",
    },
    {
      Name: "Fay, Pat",
      "Hire date": "17-AUG-05",
      Job: "Representative",
      Salary: "6000",
      "Department or unit": "20",
      "End-of_year-BONUS?": "18,68%",
      concatenated: "Fay, PatRepresentative",
    },
    {
      Name: "Mavris, Susan",
      "Hire date": "07-JUN-02",
      Job: "Salesperson",
      Salary: "6500",
      "Department or unit": "40",
      "End-of_year-BONUS?": "23,47%",
      concatenated: "Mavris, SusanSalesperson",
    },
    {
      Name: null,
      "Hire date": "07-JUN-02",
      Job: "Salesperson",
      Salary: "10000",
      "Department or unit": '"xyz"',
      "End-of_year-BONUS?": "17,63%",
      concatenated: "Salesperson",
    },
    {
      Name: "Higgins, Shelley",
      "Hire date": "07-JUN-02",
      Job: "Manager",
      Salary: "12008",
      "Department or unit": "110",
      "End-of_year-BONUS?": "17,09%",
      concatenated: "Higgins, ShelleyManager",
    },
    {
      Name: null,
      "Hire date": "07-JUN-02",
      Job: "Accountant",
      Salary: "8300",
      "Department or unit": "110",
      "End-of_year-BONUS?": "15,7%",
      concatenated: "Accountant",
    },
    {
      Name: "King, Steven",
      "Hire date": null,
      Job: "President",
      Salary: "24000",
      "Department or unit": "90",
      "End-of_year-BONUS?": "2,46%",
      concatenated: "King, StevenPresident",
    },
    {
      Name: "Kochhar, Neena",
      "Hire date": "21-SEP-05",
      Job: "Vice-president",
      Salary: '"&6%"',
      "Department or unit": "90",
      "End-of_year-BONUS?": "11,6%",
      concatenated: "Kochhar, NeenaVice-president",
    },
    {
      Name: "De Haan, Lex",
      "Hire date": null,
      Job: "Vice-president",
      Salary: "17000",
      "Department or unit": "90",
      "End-of_year-BONUS?": "23,43%",
      concatenated: "De Haan, LexVice-president",
    },
    {
      Name: "Hunold, Alexander",
      "Hire date": "03-JAN-06",
      Job: "Programmer",
      Salary: "9000",
      "Department or unit": "60",
      "End-of_year-BONUS?": "23,01%",
      concatenated: "Hunold, AlexanderProgrammer",
    },
    {
      Name: "Ernst, Bruce",
      "Hire date": "21-MAY-07",
      Job: "Programmer",
      Salary: "6000",
      "Department or unit": "60",
      "End-of_year-BONUS?": "25,91%",
      concatenated: "Ernst, BruceProgrammer",
    },
    {
      Name: "Austin, David",
      "Hire date": null,
      Job: "Programmer",
      Salary: "4800",
      "Department or unit": null,
      "End-of_year-BONUS?": "6,89%",
      concatenated: "Austin, DavidProgrammer",
    },
    {
      Name: "Pataballa, Valli",
      "Hire date": "abc",
      Job: "Programmer",
      Salary: null,
      "Department or unit": "60",
      "End-of_year-BONUS?": "1,62%",
      concatenated: "Pataballa, ValliProgrammer",
    },
    {
      Name: "Lorentz, Diana",
      "Hire date": "07-ARB-07",
      Job: "Programmer",
      Salary: "4200",
      "Department or unit": "60",
      "End-of_year-BONUS?": "13,17%",
      concatenated: "Lorentz, DianaProgrammer",
    },
    {
      Name: "Greenberg, Nancy",
      "Hire date": "17-AUG-02",
      Job: "Manager",
      Salary: "12008",
      "Department or unit": "100",
      "End-of_year-BONUS?": "74,69%",
      concatenated: "Greenberg, NancyManager",
    },
    {
      Name: "Faviet, Daniel",
      "Hire date": "16-AUG-02",
      Job: "Accountant",
      Salary: "9000",
      "Department or unit": "100",
      "End-of_year-BONUS?": "2,92%",
      concatenated: "Faviet, DanielAccountant",
    },
    {
      Name: "Chen, John",
      "Hire date": "28-SEP-05",
      Job: "Accountant",
      Salary: "8200",
      "Department or unit": "100",
      "End-of_year-BONUS?": "9,31%",
      concatenated: "Chen, JohnAccountant",
    },
    {
      Name: "Sciarra, Ismael",
      "Hire date": "30-SEP-05",
      Job: "Accountant",
      Salary: "7700",
      "Department or unit": "100",
      "End-of_year-BONUS?": "13,18%",
      concatenated: "Sciarra, IsmaelAccountant",
    },
    {
      Name: "Urman, Jose Manuel",
      "Hire date": "07-MAR-06",
      Job: "Accountant",
      Salary: "7800",
      "Department or unit": "100",
      "End-of_year-BONUS?": "1,33%",
      concatenated: "Urman, Jose ManuelAccountant",
    },
    {
      Name: "Popp, Luis",
      "Hire date": "07-DEC-07",
      Job: "Accountant",
      Salary: "6900",
      "Department or unit": "100",
      "End-of_year-BONUS?": "2,98%",
      concatenated: "Popp, LuisAccountant",
    },
    {
      Name: "Raphaely, Den",
      "Hire date": "07-DEC-02",
      Job: "Manager",
      Salary: "11000",
      "Department or unit": "30",
      "End-of_year-BONUS?": "3,35%",
      concatenated: "Raphaely, DenManager",
    },
    {
      Name: "Khoo, Alexander",
      "Hire date": "18-MAY-03",
      Job: "Clerk",
      Salary: "3100",
      "Department or unit": "30",
      "End-of_year-BONUS?": "19,81%",
      concatenated: "Khoo, AlexanderClerk",
    },
    {
      Name: "Baida, Shelli",
      "Hire date": "24-DEC-05",
      Job: "Clerk",
      Salary: "2900",
      "Department or unit": "30",
      "End-of_year-BONUS?": "11,06%",
      concatenated: "Baida, ShelliClerk",
    },
    {
      Name: "Tobias, Sigal",
      "Hire date": "24-JUL-05",
      Job: null,
      Salary: "2800",
      "Department or unit": null,
      "End-of_year-BONUS?": null,
      concatenated: "Tobias, Sigal",
    },
    {
      Name: "Himuro, Guy",
      "Hire date": "15-NOV-05",
      Job: "Clerk",
      Salary: "2600",
      "Department or unit": "30",
      "End-of_year-BONUS?": "25,98%",
      concatenated: "Himuro, GuyClerk",
    },
    {
      Name: "Colmenares, Karen",
      "Hire date": "10-AUG-07",
      Job: "Clerk",
      Salary: "2500",
      "Department or unit": "30",
      "End-of_year-BONUS?": "15,8%",
      concatenated: "Colmenares, KarenClerk",
    },
    {
      Name: "Weiss, Matthew",
      "Hire date": "18-JUL-04",
      Job: "Manager",
      Salary: "8000",
      "Department or unit": "50",
      "End-of_year-BONUS?": "25,17%",
      concatenated: "Weiss, MatthewManager",
    },
    {
      Name: "Fripp, Adam",
      "Hire date": "10-APR-05",
      Job: "Manager",
      Salary: "8200",
      "Department or unit": "50",
      "End-of_year-BONUS?": "21%",
      concatenated: "Fripp, AdamManager",
    },
    {
      Name: "Kaufling, Payam",
      "Hire date": "01-MAY-03",
      Job: "Manager",
      Salary: "7900",
      "Department or unit": null,
      "End-of_year-BONUS?": "21,33%",
      concatenated: "Kaufling, PayamManager",
    },
    {
      Name: "Vollman, Shanta",
      "Hire date": "10-OCT-05",
      Job: null,
      Salary: "6500",
      "Department or unit": "50",
      "End-of_year-BONUS?": "3,45%",
      concatenated: "Vollman, Shanta",
    },
    {
      Name: "Mourgos, Kevin",
      "Hire date": null,
      Job: "Manager",
      Salary: "5800",
      "Department or unit": "50",
      "End-of_year-BONUS?": "19,07%",
      concatenated: "Mourgos, KevinManager",
    },
    {
      Name: "Nayer, Julia",
      "Hire date": "16-JUL-05",
      Job: "Clerk",
      Salary: "3200",
      "Department or unit": "50",
      "End-of_year-BONUS?": "18,7%",
      concatenated: "Nayer, JuliaClerk",
    },
    {
      Name: "Mikkilineni, Irene",
      "Hire date": "28-SEP-06",
      Job: "Clerk",
      Salary: "2700",
      "Department or unit": "50",
      "End-of_year-BONUS?": "11,82%",
      concatenated: "Mikkilineni, IreneClerk",
    },
    {
      Name: "Landry, James",
      "Hire date": "14-JAN-07",
      Job: "Clerk",
      Salary: "2400",
      "Department or unit": "50",
      "End-of_year-BONUS?": null,
      concatenated: "Landry, JamesClerk",
    },
    {
      Name: "Markle, Steven",
      "Hire date": null,
      Job: "Clerk",
      Salary: "2200",
      "Department or unit": "50",
      "End-of_year-BONUS?": "11,26%",
      concatenated: "Markle, StevenClerk",
    },
    {
      Name: "Bissot, Laura",
      "Hire date": "20-AUG-05",
      Job: null,
      Salary: "3300",
      "Department or unit": "50",
      "End-of_year-BONUS?": "4,53%",
      concatenated: "Bissot, Laura",
    },
    {
      Name: "Atkinson, Mozhe",
      "Hire date": "30-OCT-05",
      Job: "Clerk",
      Salary: null,
      "Department or unit": "50",
      "End-of_year-BONUS?": "9,61%",
      concatenated: "Atkinson, MozheClerk",
    },
    {
      Name: "Marlow, James",
      "Hire date": "16-FEB-05",
      Job: "Clerk",
      Salary: "2500",
      "Department or unit": "50",
      "End-of_year-BONUS?": "15,74%",
      concatenated: "Marlow, JamesClerk",
    },
    {
      Name: "Olson, TJ",
      "Hire date": "10-APR-07",
      Job: "Clerk",
      Salary: "2100",
      "Department or unit": null,
      "End-of_year-BONUS?": "22,3%",
      concatenated: "Olson, TJClerk",
    },
    {
      Name: null,
      "Hire date": "14-JUN-04",
      Job: "Clerk",
      Salary: "3300",
      "Department or unit": "50",
      "End-of_year-BONUS?": "18,54%",
      concatenated: "Clerk",
    },
    {
      Name: "Rogers, Michael",
      "Hire date": "26-AUG-06",
      Job: "Clerk",
      Salary: "2900",
      "Department or unit": "50",
      "End-of_year-BONUS?": null,
      concatenated: "Rogers, MichaelClerk",
    },
    {
      Name: "Gee, Ki",
      "Hire date": "12-DEC-07",
      Job: null,
      Salary: "2400",
      "Department or unit": "50",
      "End-of_year-BONUS?": "12,64%",
      concatenated: "Gee, Ki",
    },
    {
      Name: "Philtanker, Hazel",
      "Hire date": "06-FEB-08",
      Job: "Clerk",
      Salary: "2200",
      "Department or unit": null,
      "End-of_year-BONUS?": "24,17%",
      concatenated: "Philtanker, HazelClerk",
    },
    {
      Name: "Ladwig, Renske",
      "Hire date": "14-JUL-03",
      Job: null,
      Salary: "3600",
      "Department or unit": "50",
      "End-of_year-BONUS?": "17,86%",
      concatenated: "Ladwig, Renske",
    },
    {
      Name: "Stiles, Stephen",
      "Hire date": "26-OCT-05",
      Job: "Clerk",
      Salary: "3200",
      "Department or unit": "50",
      "End-of_year-BONUS?": null,
      concatenated: "Stiles, StephenClerk",
    },
    {
      Name: "Seo, John",
      "Hire date": "12-FEB-06",
      Job: "Clerk",
      Salary: "2700",
      "Department or unit": "50",
      "End-of_year-BONUS?": "0,16%",
      concatenated: "Seo, JohnClerk",
    },
    {
      Name: "Patel, Joshua",
      "Hire date": "06-APR-06",
      Job: "Clerk",
      Salary: "2500",
      "Department or unit": "50",
      "End-of_year-BONUS?": "16,19%",
      concatenated: "Patel, JoshuaClerk",
    },
  ]);
  await sdb.done();
});

Deno.test("should concatenate multiple columns in a new one with a separator", async () => {
  const sdb = new SimpleDB();
  const table = sdb.newTable("employees");
  await table.loadData(["test/data/files/employees.json"]);
  await table.concatenate(["Name", "Job"], "concatenatedWithSeparator", {
    separator: "-",
  });
  const data = await table.getData();

  assertEquals(data, [
    {
      Name: "OConnell, Donald",
      "Hire date": "21-JUN-07",
      Job: "Clerk",
      Salary: "2600",
      "Department or unit": "50",
      "End-of_year-BONUS?": "1,94%",
      concatenatedWithSeparator: "OConnell, Donald-Clerk",
    },
    {
      Name: "OConnell, Donald",
      "Hire date": "21-JUN-07",
      Job: "Clerk",
      Salary: "2600",
      "Department or unit": "50",
      "End-of_year-BONUS?": "1,94%",
      concatenatedWithSeparator: "OConnell, Donald-Clerk",
    },
    {
      Name: "Grant, Douglas",
      "Hire date": "13-JAN-08",
      Job: "Clerk",
      Salary: null,
      "Department or unit": "50",
      "End-of_year-BONUS?": "23,39%",
      concatenatedWithSeparator: "Grant, Douglas-Clerk",
    },
    {
      Name: null,
      "Hire date": "17-SEP-03",
      Job: "Assistant",
      Salary: "4400",
      "Department or unit": "10",
      "End-of_year-BONUS?": "17,51%",
      concatenatedWithSeparator: "Assistant",
    },
    {
      Name: "Hartstein, Michael",
      "Hire date": "17-FEB-04",
      Job: "Manager",
      Salary: "13000",
      "Department or unit": "20",
      "End-of_year-BONUS?": "2,71%",
      concatenatedWithSeparator: "Hartstein, Michael-Manager",
    },
    {
      Name: "Fay, Pat",
      "Hire date": "17-AUG-05",
      Job: "Representative",
      Salary: "6000",
      "Department or unit": "20",
      "End-of_year-BONUS?": "18,68%",
      concatenatedWithSeparator: "Fay, Pat-Representative",
    },
    {
      Name: "Mavris, Susan",
      "Hire date": "07-JUN-02",
      Job: "Salesperson",
      Salary: "6500",
      "Department or unit": "40",
      "End-of_year-BONUS?": "23,47%",
      concatenatedWithSeparator: "Mavris, Susan-Salesperson",
    },
    {
      Name: null,
      "Hire date": "07-JUN-02",
      Job: "Salesperson",
      Salary: "10000",
      "Department or unit": '"xyz"',
      "End-of_year-BONUS?": "17,63%",
      concatenatedWithSeparator: "Salesperson",
    },
    {
      Name: "Higgins, Shelley",
      "Hire date": "07-JUN-02",
      Job: "Manager",
      Salary: "12008",
      "Department or unit": "110",
      "End-of_year-BONUS?": "17,09%",
      concatenatedWithSeparator: "Higgins, Shelley-Manager",
    },
    {
      Name: null,
      "Hire date": "07-JUN-02",
      Job: "Accountant",
      Salary: "8300",
      "Department or unit": "110",
      "End-of_year-BONUS?": "15,7%",
      concatenatedWithSeparator: "Accountant",
    },
    {
      Name: "King, Steven",
      "Hire date": null,
      Job: "President",
      Salary: "24000",
      "Department or unit": "90",
      "End-of_year-BONUS?": "2,46%",
      concatenatedWithSeparator: "King, Steven-President",
    },
    {
      Name: "Kochhar, Neena",
      "Hire date": "21-SEP-05",
      Job: "Vice-president",
      Salary: '"&6%"',
      "Department or unit": "90",
      "End-of_year-BONUS?": "11,6%",
      concatenatedWithSeparator: "Kochhar, Neena-Vice-president",
    },
    {
      Name: "De Haan, Lex",
      "Hire date": null,
      Job: "Vice-president",
      Salary: "17000",
      "Department or unit": "90",
      "End-of_year-BONUS?": "23,43%",
      concatenatedWithSeparator: "De Haan, Lex-Vice-president",
    },
    {
      Name: "Hunold, Alexander",
      "Hire date": "03-JAN-06",
      Job: "Programmer",
      Salary: "9000",
      "Department or unit": "60",
      "End-of_year-BONUS?": "23,01%",
      concatenatedWithSeparator: "Hunold, Alexander-Programmer",
    },
    {
      Name: "Ernst, Bruce",
      "Hire date": "21-MAY-07",
      Job: "Programmer",
      Salary: "6000",
      "Department or unit": "60",
      "End-of_year-BONUS?": "25,91%",
      concatenatedWithSeparator: "Ernst, Bruce-Programmer",
    },
    {
      Name: "Austin, David",
      "Hire date": null,
      Job: "Programmer",
      Salary: "4800",
      "Department or unit": null,
      "End-of_year-BONUS?": "6,89%",
      concatenatedWithSeparator: "Austin, David-Programmer",
    },
    {
      Name: "Pataballa, Valli",
      "Hire date": "abc",
      Job: "Programmer",
      Salary: null,
      "Department or unit": "60",
      "End-of_year-BONUS?": "1,62%",
      concatenatedWithSeparator: "Pataballa, Valli-Programmer",
    },
    {
      Name: "Lorentz, Diana",
      "Hire date": "07-ARB-07",
      Job: "Programmer",
      Salary: "4200",
      "Department or unit": "60",
      "End-of_year-BONUS?": "13,17%",
      concatenatedWithSeparator: "Lorentz, Diana-Programmer",
    },
    {
      Name: "Greenberg, Nancy",
      "Hire date": "17-AUG-02",
      Job: "Manager",
      Salary: "12008",
      "Department or unit": "100",
      "End-of_year-BONUS?": "74,69%",
      concatenatedWithSeparator: "Greenberg, Nancy-Manager",
    },
    {
      Name: "Faviet, Daniel",
      "Hire date": "16-AUG-02",
      Job: "Accountant",
      Salary: "9000",
      "Department or unit": "100",
      "End-of_year-BONUS?": "2,92%",
      concatenatedWithSeparator: "Faviet, Daniel-Accountant",
    },
    {
      Name: "Chen, John",
      "Hire date": "28-SEP-05",
      Job: "Accountant",
      Salary: "8200",
      "Department or unit": "100",
      "End-of_year-BONUS?": "9,31%",
      concatenatedWithSeparator: "Chen, John-Accountant",
    },
    {
      Name: "Sciarra, Ismael",
      "Hire date": "30-SEP-05",
      Job: "Accountant",
      Salary: "7700",
      "Department or unit": "100",
      "End-of_year-BONUS?": "13,18%",
      concatenatedWithSeparator: "Sciarra, Ismael-Accountant",
    },
    {
      Name: "Urman, Jose Manuel",
      "Hire date": "07-MAR-06",
      Job: "Accountant",
      Salary: "7800",
      "Department or unit": "100",
      "End-of_year-BONUS?": "1,33%",
      concatenatedWithSeparator: "Urman, Jose Manuel-Accountant",
    },
    {
      Name: "Popp, Luis",
      "Hire date": "07-DEC-07",
      Job: "Accountant",
      Salary: "6900",
      "Department or unit": "100",
      "End-of_year-BONUS?": "2,98%",
      concatenatedWithSeparator: "Popp, Luis-Accountant",
    },
    {
      Name: "Raphaely, Den",
      "Hire date": "07-DEC-02",
      Job: "Manager",
      Salary: "11000",
      "Department or unit": "30",
      "End-of_year-BONUS?": "3,35%",
      concatenatedWithSeparator: "Raphaely, Den-Manager",
    },
    {
      Name: "Khoo, Alexander",
      "Hire date": "18-MAY-03",
      Job: "Clerk",
      Salary: "3100",
      "Department or unit": "30",
      "End-of_year-BONUS?": "19,81%",
      concatenatedWithSeparator: "Khoo, Alexander-Clerk",
    },
    {
      Name: "Baida, Shelli",
      "Hire date": "24-DEC-05",
      Job: "Clerk",
      Salary: "2900",
      "Department or unit": "30",
      "End-of_year-BONUS?": "11,06%",
      concatenatedWithSeparator: "Baida, Shelli-Clerk",
    },
    {
      Name: "Tobias, Sigal",
      "Hire date": "24-JUL-05",
      Job: null,
      Salary: "2800",
      "Department or unit": null,
      "End-of_year-BONUS?": null,
      concatenatedWithSeparator: "Tobias, Sigal",
    },
    {
      Name: "Himuro, Guy",
      "Hire date": "15-NOV-05",
      Job: "Clerk",
      Salary: "2600",
      "Department or unit": "30",
      "End-of_year-BONUS?": "25,98%",
      concatenatedWithSeparator: "Himuro, Guy-Clerk",
    },
    {
      Name: "Colmenares, Karen",
      "Hire date": "10-AUG-07",
      Job: "Clerk",
      Salary: "2500",
      "Department or unit": "30",
      "End-of_year-BONUS?": "15,8%",
      concatenatedWithSeparator: "Colmenares, Karen-Clerk",
    },
    {
      Name: "Weiss, Matthew",
      "Hire date": "18-JUL-04",
      Job: "Manager",
      Salary: "8000",
      "Department or unit": "50",
      "End-of_year-BONUS?": "25,17%",
      concatenatedWithSeparator: "Weiss, Matthew-Manager",
    },
    {
      Name: "Fripp, Adam",
      "Hire date": "10-APR-05",
      Job: "Manager",
      Salary: "8200",
      "Department or unit": "50",
      "End-of_year-BONUS?": "21%",
      concatenatedWithSeparator: "Fripp, Adam-Manager",
    },
    {
      Name: "Kaufling, Payam",
      "Hire date": "01-MAY-03",
      Job: "Manager",
      Salary: "7900",
      "Department or unit": null,
      "End-of_year-BONUS?": "21,33%",
      concatenatedWithSeparator: "Kaufling, Payam-Manager",
    },
    {
      Name: "Vollman, Shanta",
      "Hire date": "10-OCT-05",
      Job: null,
      Salary: "6500",
      "Department or unit": "50",
      "End-of_year-BONUS?": "3,45%",
      concatenatedWithSeparator: "Vollman, Shanta",
    },
    {
      Name: "Mourgos, Kevin",
      "Hire date": null,
      Job: "Manager",
      Salary: "5800",
      "Department or unit": "50",
      "End-of_year-BONUS?": "19,07%",
      concatenatedWithSeparator: "Mourgos, Kevin-Manager",
    },
    {
      Name: "Nayer, Julia",
      "Hire date": "16-JUL-05",
      Job: "Clerk",
      Salary: "3200",
      "Department or unit": "50",
      "End-of_year-BONUS?": "18,7%",
      concatenatedWithSeparator: "Nayer, Julia-Clerk",
    },
    {
      Name: "Mikkilineni, Irene",
      "Hire date": "28-SEP-06",
      Job: "Clerk",
      Salary: "2700",
      "Department or unit": "50",
      "End-of_year-BONUS?": "11,82%",
      concatenatedWithSeparator: "Mikkilineni, Irene-Clerk",
    },
    {
      Name: "Landry, James",
      "Hire date": "14-JAN-07",
      Job: "Clerk",
      Salary: "2400",
      "Department or unit": "50",
      "End-of_year-BONUS?": null,
      concatenatedWithSeparator: "Landry, James-Clerk",
    },
    {
      Name: "Markle, Steven",
      "Hire date": null,
      Job: "Clerk",
      Salary: "2200",
      "Department or unit": "50",
      "End-of_year-BONUS?": "11,26%",
      concatenatedWithSeparator: "Markle, Steven-Clerk",
    },
    {
      Name: "Bissot, Laura",
      "Hire date": "20-AUG-05",
      Job: null,
      Salary: "3300",
      "Department or unit": "50",
      "End-of_year-BONUS?": "4,53%",
      concatenatedWithSeparator: "Bissot, Laura",
    },
    {
      Name: "Atkinson, Mozhe",
      "Hire date": "30-OCT-05",
      Job: "Clerk",
      Salary: null,
      "Department or unit": "50",
      "End-of_year-BONUS?": "9,61%",
      concatenatedWithSeparator: "Atkinson, Mozhe-Clerk",
    },
    {
      Name: "Marlow, James",
      "Hire date": "16-FEB-05",
      Job: "Clerk",
      Salary: "2500",
      "Department or unit": "50",
      "End-of_year-BONUS?": "15,74%",
      concatenatedWithSeparator: "Marlow, James-Clerk",
    },
    {
      Name: "Olson, TJ",
      "Hire date": "10-APR-07",
      Job: "Clerk",
      Salary: "2100",
      "Department or unit": null,
      "End-of_year-BONUS?": "22,3%",
      concatenatedWithSeparator: "Olson, TJ-Clerk",
    },
    {
      Name: null,
      "Hire date": "14-JUN-04",
      Job: "Clerk",
      Salary: "3300",
      "Department or unit": "50",
      "End-of_year-BONUS?": "18,54%",
      concatenatedWithSeparator: "Clerk",
    },
    {
      Name: "Rogers, Michael",
      "Hire date": "26-AUG-06",
      Job: "Clerk",
      Salary: "2900",
      "Department or unit": "50",
      "End-of_year-BONUS?": null,
      concatenatedWithSeparator: "Rogers, Michael-Clerk",
    },
    {
      Name: "Gee, Ki",
      "Hire date": "12-DEC-07",
      Job: null,
      Salary: "2400",
      "Department or unit": "50",
      "End-of_year-BONUS?": "12,64%",
      concatenatedWithSeparator: "Gee, Ki",
    },
    {
      Name: "Philtanker, Hazel",
      "Hire date": "06-FEB-08",
      Job: "Clerk",
      Salary: "2200",
      "Department or unit": null,
      "End-of_year-BONUS?": "24,17%",
      concatenatedWithSeparator: "Philtanker, Hazel-Clerk",
    },
    {
      Name: "Ladwig, Renske",
      "Hire date": "14-JUL-03",
      Job: null,
      Salary: "3600",
      "Department or unit": "50",
      "End-of_year-BONUS?": "17,86%",
      concatenatedWithSeparator: "Ladwig, Renske",
    },
    {
      Name: "Stiles, Stephen",
      "Hire date": "26-OCT-05",
      Job: "Clerk",
      Salary: "3200",
      "Department or unit": "50",
      "End-of_year-BONUS?": null,
      concatenatedWithSeparator: "Stiles, Stephen-Clerk",
    },
    {
      Name: "Seo, John",
      "Hire date": "12-FEB-06",
      Job: "Clerk",
      Salary: "2700",
      "Department or unit": "50",
      "End-of_year-BONUS?": "0,16%",
      concatenatedWithSeparator: "Seo, John-Clerk",
    },
    {
      Name: "Patel, Joshua",
      "Hire date": "06-APR-06",
      Job: "Clerk",
      Salary: "2500",
      "Department or unit": "50",
      "End-of_year-BONUS?": "16,19%",
      concatenatedWithSeparator: "Patel, Joshua-Clerk",
    },
  ]);
  await sdb.done();
});
