import assert from "assert"
import SimpleDB from "../../../src/class/SimpleDB.js"

describe("removeColumns", () => {
    let sdb: SimpleDB
    before(async function () {
        sdb = new SimpleDB()
    })
    after(async function () {
        await sdb.done()
    })

    it("should remove one column", async () => {
        const table = sdb.newTable()
        await table.loadData("test/data/files/employees.csv")
        await table.cleanColumnNames()

        await table.removeColumns("hireDate")
        const data = await table.getData()

        assert.deepStrictEqual(data, [
            {
                name: "OConnell, Donald",
                job: "Clerk",
                salary: "2600",
                departmentOrUnit: "50",
                endOfYearBonus: "1,94%",
            },
            {
                name: "OConnell, Donald",
                job: "Clerk",
                salary: "2600",
                departmentOrUnit: "50",
                endOfYearBonus: "1,94%",
            },
            {
                name: "Grant, Douglas",
                job: "Clerk",
                salary: "NaN",
                departmentOrUnit: "50",
                endOfYearBonus: "23,39%",
            },
            {
                name: null,
                job: "Assistant",
                salary: "4400",
                departmentOrUnit: "10",
                endOfYearBonus: "17,51%",
            },
            {
                name: "Hartstein, Michael",
                job: "Manager",
                salary: "13000",
                departmentOrUnit: "20",
                endOfYearBonus: "2,71%",
            },
            {
                name: "Fay, Pat",
                job: "Representative",
                salary: "6000",
                departmentOrUnit: "20",
                endOfYearBonus: "18,68%",
            },
            {
                name: "Mavris, Susan",
                job: "Salesperson",
                salary: "6500",
                departmentOrUnit: "40",
                endOfYearBonus: "23,47%",
            },
            {
                name: "NaN",
                job: "Salesperson",
                salary: "10000",
                departmentOrUnit: "xyz",
                endOfYearBonus: "17,63%",
            },
            {
                name: "Higgins, Shelley",
                job: "Manager",
                salary: "12008",
                departmentOrUnit: "110",
                endOfYearBonus: "17,09%",
            },
            {
                name: "null",
                job: "Accountant",
                salary: "8300",
                departmentOrUnit: "110",
                endOfYearBonus: "15,7%",
            },
            {
                name: "King, Steven",
                job: "President",
                salary: "24000",
                departmentOrUnit: "90",
                endOfYearBonus: "2,46%",
            },
            {
                name: "Kochhar, Neena",
                job: "Vice-president",
                salary: "&6%",
                departmentOrUnit: "90",
                endOfYearBonus: "11,6%",
            },
            {
                name: "De Haan, Lex",
                job: "Vice-president",
                salary: "17000",
                departmentOrUnit: "90",
                endOfYearBonus: "23,43%",
            },
            {
                name: "Hunold, Alexander",
                job: "Programmer",
                salary: "9000",
                departmentOrUnit: "60",
                endOfYearBonus: "23,01%",
            },
            {
                name: "Ernst, Bruce",
                job: "Programmer",
                salary: "6000",
                departmentOrUnit: "60",
                endOfYearBonus: "25,91%",
            },
            {
                name: "Austin, David",
                job: "Programmer",
                salary: "4800",
                departmentOrUnit: "null",
                endOfYearBonus: "6,89%",
            },
            {
                name: "Pataballa, Valli",
                job: "Programmer",
                salary: null,
                departmentOrUnit: "60",
                endOfYearBonus: "1,62%",
            },
            {
                name: "Lorentz, Diana",
                job: "Programmer",
                salary: "4200",
                departmentOrUnit: "60",
                endOfYearBonus: "13,17%",
            },
            {
                name: "Greenberg, Nancy",
                job: "Manager",
                salary: "12008",
                departmentOrUnit: "100",
                endOfYearBonus: "74,69%",
            },
            {
                name: "Faviet, Daniel",
                job: "Accountant",
                salary: "9000",
                departmentOrUnit: "100",
                endOfYearBonus: "2,92%",
            },
            {
                name: "Chen, John",
                job: "Accountant",
                salary: "8200",
                departmentOrUnit: "100",
                endOfYearBonus: "9,31%",
            },
            {
                name: "Sciarra, Ismael",
                job: "Accountant",
                salary: "7700",
                departmentOrUnit: "100",
                endOfYearBonus: "13,18%",
            },
            {
                name: "Urman, Jose Manuel",
                job: "Accountant",
                salary: "7800",
                departmentOrUnit: "100",
                endOfYearBonus: "1,33%",
            },
            {
                name: "Popp, Luis",
                job: "Accountant",
                salary: "6900",
                departmentOrUnit: "100",
                endOfYearBonus: "2,98%",
            },
            {
                name: "Raphaely, Den",
                job: "Manager",
                salary: "11000",
                departmentOrUnit: "30",
                endOfYearBonus: "3,35%",
            },
            {
                name: "Khoo, Alexander",
                job: "Clerk",
                salary: "3100",
                departmentOrUnit: "30",
                endOfYearBonus: "19,81%",
            },
            {
                name: "Baida, Shelli",
                job: "Clerk",
                salary: "2900",
                departmentOrUnit: "30",
                endOfYearBonus: "11,06%",
            },
            {
                name: "Tobias, Sigal",
                job: "NaN",
                salary: "2800",
                departmentOrUnit: null,
                endOfYearBonus: "undefined",
            },
            {
                name: "Himuro, Guy",
                job: "Clerk",
                salary: "2600",
                departmentOrUnit: "30",
                endOfYearBonus: "25,98%",
            },
            {
                name: "Colmenares, Karen",
                job: "Clerk",
                salary: "2500",
                departmentOrUnit: "30",
                endOfYearBonus: "15,8%",
            },
            {
                name: "Weiss, Matthew",
                job: "Manager",
                salary: "8000",
                departmentOrUnit: "50",
                endOfYearBonus: "25,17%",
            },
            {
                name: "Fripp, Adam",
                job: "Manager",
                salary: "8200",
                departmentOrUnit: "50",
                endOfYearBonus: "21%",
            },
            {
                name: "Kaufling, Payam",
                job: "Manager",
                salary: "7900",
                departmentOrUnit: "undefined",
                endOfYearBonus: "21,33%",
            },
            {
                name: "Vollman, Shanta",
                job: "null",
                salary: "6500",
                departmentOrUnit: "50",
                endOfYearBonus: "3,45%",
            },
            {
                name: "Mourgos, Kevin",
                job: "Manager",
                salary: "5800",
                departmentOrUnit: "50",
                endOfYearBonus: "19,07%",
            },
            {
                name: "Nayer, Julia",
                job: "Clerk",
                salary: "3200",
                departmentOrUnit: "50",
                endOfYearBonus: "18,7%",
            },
            {
                name: "Mikkilineni, Irene",
                job: "Clerk",
                salary: "2700",
                departmentOrUnit: "50",
                endOfYearBonus: "11,82%",
            },
            {
                name: "Landry, James",
                job: "Clerk",
                salary: "2400",
                departmentOrUnit: "50",
                endOfYearBonus: "NaN",
            },
            {
                name: "Markle, Steven",
                job: "Clerk",
                salary: "2200",
                departmentOrUnit: "50",
                endOfYearBonus: "11,26%",
            },
            {
                name: "Bissot, Laura",
                job: "undefined",
                salary: "3300",
                departmentOrUnit: "50",
                endOfYearBonus: "4,53%",
            },
            {
                name: "Atkinson, Mozhe",
                job: "Clerk",
                salary: "undefined",
                departmentOrUnit: "50",
                endOfYearBonus: "9,61%",
            },
            {
                name: "Marlow, James",
                job: "Clerk",
                salary: "2500",
                departmentOrUnit: "50",
                endOfYearBonus: "15,74%",
            },
            {
                name: "Olson, TJ",
                job: "Clerk",
                salary: "2100",
                departmentOrUnit: "null",
                endOfYearBonus: "22,3%",
            },
            {
                name: "undefined",
                job: "Clerk",
                salary: "3300",
                departmentOrUnit: "50",
                endOfYearBonus: "18,54%",
            },
            {
                name: "Rogers, Michael",
                job: "Clerk",
                salary: "2900",
                departmentOrUnit: "50",
                endOfYearBonus: "null",
            },
            {
                name: "Gee, Ki",
                job: "NaN",
                salary: "2400",
                departmentOrUnit: "50",
                endOfYearBonus: "12,64%",
            },
            {
                name: "Philtanker, Hazel",
                job: "Clerk",
                salary: "2200",
                departmentOrUnit: "NaN",
                endOfYearBonus: "24,17%",
            },
            {
                name: "Ladwig, Renske",
                job: null,
                salary: "3600",
                departmentOrUnit: "50",
                endOfYearBonus: "17,86%",
            },
            {
                name: "Stiles, Stephen",
                job: "Clerk",
                salary: "3200",
                departmentOrUnit: "50",
                endOfYearBonus: null,
            },
            {
                name: "Seo, John",
                job: "Clerk",
                salary: "2700",
                departmentOrUnit: "50",
                endOfYearBonus: "0,16%",
            },
            {
                name: "Patel, Joshua",
                job: "Clerk",
                salary: "2500",
                departmentOrUnit: "50",
                endOfYearBonus: "16,19%",
            },
        ])
    })

    it("should remove multiple columns", async () => {
        const table = sdb.newTable()
        await table.loadData("test/data/files/employees.csv")
        await table.cleanColumnNames()
        await table.removeColumns(["job", "salary"])
        const data = await table.getData()

        assert.deepStrictEqual(data, [
            {
                name: "OConnell, Donald",
                hireDate: "21-JUN-07",
                departmentOrUnit: "50",
                endOfYearBonus: "1,94%",
            },
            {
                name: "OConnell, Donald",
                hireDate: "21-JUN-07",
                departmentOrUnit: "50",
                endOfYearBonus: "1,94%",
            },
            {
                name: "Grant, Douglas",
                hireDate: "13-JAN-08",
                departmentOrUnit: "50",
                endOfYearBonus: "23,39%",
            },
            {
                name: null,
                hireDate: "17-SEP-03",
                departmentOrUnit: "10",
                endOfYearBonus: "17,51%",
            },
            {
                name: "Hartstein, Michael",
                hireDate: "17-FEB-04",
                departmentOrUnit: "20",
                endOfYearBonus: "2,71%",
            },
            {
                name: "Fay, Pat",
                hireDate: "17-AUG-05",
                departmentOrUnit: "20",
                endOfYearBonus: "18,68%",
            },
            {
                name: "Mavris, Susan",
                hireDate: "07-JUN-02",
                departmentOrUnit: "40",
                endOfYearBonus: "23,47%",
            },
            {
                name: "NaN",
                hireDate: "07-JUN-02",
                departmentOrUnit: "xyz",
                endOfYearBonus: "17,63%",
            },
            {
                name: "Higgins, Shelley",
                hireDate: "07-JUN-02",
                departmentOrUnit: "110",
                endOfYearBonus: "17,09%",
            },
            {
                name: "null",
                hireDate: "07-JUN-02",
                departmentOrUnit: "110",
                endOfYearBonus: "15,7%",
            },
            {
                name: "King, Steven",
                hireDate: null,
                departmentOrUnit: "90",
                endOfYearBonus: "2,46%",
            },
            {
                name: "Kochhar, Neena",
                hireDate: "21-SEP-05",
                departmentOrUnit: "90",
                endOfYearBonus: "11,6%",
            },
            {
                name: "De Haan, Lex",
                hireDate: "null",
                departmentOrUnit: "90",
                endOfYearBonus: "23,43%",
            },
            {
                name: "Hunold, Alexander",
                hireDate: "03-JAN-06",
                departmentOrUnit: "60",
                endOfYearBonus: "23,01%",
            },
            {
                name: "Ernst, Bruce",
                hireDate: "21-MAY-07",
                departmentOrUnit: "60",
                endOfYearBonus: "25,91%",
            },
            {
                name: "Austin, David",
                hireDate: "NaN",
                departmentOrUnit: "null",
                endOfYearBonus: "6,89%",
            },
            {
                name: "Pataballa, Valli",
                hireDate: "abc",
                departmentOrUnit: "60",
                endOfYearBonus: "1,62%",
            },
            {
                name: "Lorentz, Diana",
                hireDate: "07-ARB-07",
                departmentOrUnit: "60",
                endOfYearBonus: "13,17%",
            },
            {
                name: "Greenberg, Nancy",
                hireDate: "17-AUG-02",
                departmentOrUnit: "100",
                endOfYearBonus: "74,69%",
            },
            {
                name: "Faviet, Daniel",
                hireDate: "16-AUG-02",
                departmentOrUnit: "100",
                endOfYearBonus: "2,92%",
            },
            {
                name: "Chen, John",
                hireDate: "28-SEP-05",
                departmentOrUnit: "100",
                endOfYearBonus: "9,31%",
            },
            {
                name: "Sciarra, Ismael",
                hireDate: "30-SEP-05",
                departmentOrUnit: "100",
                endOfYearBonus: "13,18%",
            },
            {
                name: "Urman, Jose Manuel",
                hireDate: "07-MAR-06",
                departmentOrUnit: "100",
                endOfYearBonus: "1,33%",
            },
            {
                name: "Popp, Luis",
                hireDate: "07-DEC-07",
                departmentOrUnit: "100",
                endOfYearBonus: "2,98%",
            },
            {
                name: "Raphaely, Den",
                hireDate: "07-DEC-02",
                departmentOrUnit: "30",
                endOfYearBonus: "3,35%",
            },
            {
                name: "Khoo, Alexander",
                hireDate: "18-MAY-03",
                departmentOrUnit: "30",
                endOfYearBonus: "19,81%",
            },
            {
                name: "Baida, Shelli",
                hireDate: "24-DEC-05",
                departmentOrUnit: "30",
                endOfYearBonus: "11,06%",
            },
            {
                name: "Tobias, Sigal",
                hireDate: "24-JUL-05",
                departmentOrUnit: null,
                endOfYearBonus: "undefined",
            },
            {
                name: "Himuro, Guy",
                hireDate: "15-NOV-05",
                departmentOrUnit: "30",
                endOfYearBonus: "25,98%",
            },
            {
                name: "Colmenares, Karen",
                hireDate: "10-AUG-07",
                departmentOrUnit: "30",
                endOfYearBonus: "15,8%",
            },
            {
                name: "Weiss, Matthew",
                hireDate: "18-JUL-04",
                departmentOrUnit: "50",
                endOfYearBonus: "25,17%",
            },
            {
                name: "Fripp, Adam",
                hireDate: "10-APR-05",
                departmentOrUnit: "50",
                endOfYearBonus: "21%",
            },
            {
                name: "Kaufling, Payam",
                hireDate: "01-MAY-03",
                departmentOrUnit: "undefined",
                endOfYearBonus: "21,33%",
            },
            {
                name: "Vollman, Shanta",
                hireDate: "10-OCT-05",
                departmentOrUnit: "50",
                endOfYearBonus: "3,45%",
            },
            {
                name: "Mourgos, Kevin",
                hireDate: "undefined",
                departmentOrUnit: "50",
                endOfYearBonus: "19,07%",
            },
            {
                name: "Nayer, Julia",
                hireDate: "16-JUL-05",
                departmentOrUnit: "50",
                endOfYearBonus: "18,7%",
            },
            {
                name: "Mikkilineni, Irene",
                hireDate: "28-SEP-06",
                departmentOrUnit: "50",
                endOfYearBonus: "11,82%",
            },
            {
                name: "Landry, James",
                hireDate: "14-JAN-07",
                departmentOrUnit: "50",
                endOfYearBonus: "NaN",
            },
            {
                name: "Markle, Steven",
                hireDate: "NaN",
                departmentOrUnit: "50",
                endOfYearBonus: "11,26%",
            },
            {
                name: "Bissot, Laura",
                hireDate: "20-AUG-05",
                departmentOrUnit: "50",
                endOfYearBonus: "4,53%",
            },
            {
                name: "Atkinson, Mozhe",
                hireDate: "30-OCT-05",
                departmentOrUnit: "50",
                endOfYearBonus: "9,61%",
            },
            {
                name: "Marlow, James",
                hireDate: "16-FEB-05",
                departmentOrUnit: "50",
                endOfYearBonus: "15,74%",
            },
            {
                name: "Olson, TJ",
                hireDate: "10-APR-07",
                departmentOrUnit: "null",
                endOfYearBonus: "22,3%",
            },
            {
                name: "undefined",
                hireDate: "14-JUN-04",
                departmentOrUnit: "50",
                endOfYearBonus: "18,54%",
            },
            {
                name: "Rogers, Michael",
                hireDate: "26-AUG-06",
                departmentOrUnit: "50",
                endOfYearBonus: "null",
            },
            {
                name: "Gee, Ki",
                hireDate: "12-DEC-07",
                departmentOrUnit: "50",
                endOfYearBonus: "12,64%",
            },
            {
                name: "Philtanker, Hazel",
                hireDate: "06-FEB-08",
                departmentOrUnit: "NaN",
                endOfYearBonus: "24,17%",
            },
            {
                name: "Ladwig, Renske",
                hireDate: "14-JUL-03",
                departmentOrUnit: "50",
                endOfYearBonus: "17,86%",
            },
            {
                name: "Stiles, Stephen",
                hireDate: "26-OCT-05",
                departmentOrUnit: "50",
                endOfYearBonus: null,
            },
            {
                name: "Seo, John",
                hireDate: "12-FEB-06",
                departmentOrUnit: "50",
                endOfYearBonus: "0,16%",
            },
            {
                name: "Patel, Joshua",
                hireDate: "06-APR-06",
                departmentOrUnit: "50",
                endOfYearBonus: "16,19%",
            },
        ])
    })
})
