import { assertEquals } from "jsr:@std/assert";
import SimpleDB from "../../../src/class/SimpleDB.ts";

const sdb = new SimpleDB();

Deno.test("should replace the text in one column", async () => {
  const table = sdb.newTable();
  await table.loadData(["test/data/files/employees.csv"]);
  await table.cleanColumnNames();

  await table.replace(["name", "endOfYearBonus"], { "%": "" });

  const data = await table.getData();

  assertEquals(data, [
    {
      name: "OConnell, Donald",
      hireDate: "21-JUN-07",
      job: "Clerk",
      salary: "2600",
      departmentOrUnit: "50",
      endOfYearBonus: "1,94",
    },
    {
      name: "OConnell, Donald",
      hireDate: "21-JUN-07",
      job: "Clerk",
      salary: "2600",
      departmentOrUnit: "50",
      endOfYearBonus: "1,94",
    },
    {
      name: "Grant, Douglas",
      hireDate: "13-JAN-08",
      job: "Clerk",
      salary: "NaN",
      departmentOrUnit: "50",
      endOfYearBonus: "23,39",
    },
    {
      name: null,
      hireDate: "17-SEP-03",
      job: "Assistant",
      salary: "4400",
      departmentOrUnit: "10",
      endOfYearBonus: "17,51",
    },
    {
      name: "Hartstein, Michael",
      hireDate: "17-FEB-04",
      job: "Manager",
      salary: "13000",
      departmentOrUnit: "20",
      endOfYearBonus: "2,71",
    },
    {
      name: "Fay, Pat",
      hireDate: "17-AUG-05",
      job: "Representative",
      salary: "6000",
      departmentOrUnit: "20",
      endOfYearBonus: "18,68",
    },
    {
      name: "Mavris, Susan",
      hireDate: "07-JUN-02",
      job: "Salesperson",
      salary: "6500",
      departmentOrUnit: "40",
      endOfYearBonus: "23,47",
    },
    {
      name: "NaN",
      hireDate: "07-JUN-02",
      job: "Salesperson",
      salary: "10000",
      departmentOrUnit: "xyz",
      endOfYearBonus: "17,63",
    },
    {
      name: "Higgins, Shelley",
      hireDate: "07-JUN-02",
      job: "Manager",
      salary: "12008",
      departmentOrUnit: "110",
      endOfYearBonus: "17,09",
    },
    {
      name: "null",
      hireDate: "07-JUN-02",
      job: "Accountant",
      salary: "8300",
      departmentOrUnit: "110",
      endOfYearBonus: "15,7",
    },
    {
      name: "King, Steven",
      hireDate: null,
      job: "President",
      salary: "24000",
      departmentOrUnit: "90",
      endOfYearBonus: "2,46",
    },
    {
      name: "Kochhar, Neena",
      hireDate: "21-SEP-05",
      job: "Vice-president",
      salary: "&6%",
      departmentOrUnit: "90",
      endOfYearBonus: "11,6",
    },
    {
      name: "De Haan, Lex",
      hireDate: "null",
      job: "Vice-president",
      salary: "17000",
      departmentOrUnit: "90",
      endOfYearBonus: "23,43",
    },
    {
      name: "Hunold, Alexander",
      hireDate: "03-JAN-06",
      job: "Programmer",
      salary: "9000",
      departmentOrUnit: "60",
      endOfYearBonus: "23,01",
    },
    {
      name: "Ernst, Bruce",
      hireDate: "21-MAY-07",
      job: "Programmer",
      salary: "6000",
      departmentOrUnit: "60",
      endOfYearBonus: "25,91",
    },
    {
      name: "Austin, David",
      hireDate: "NaN",
      job: "Programmer",
      salary: "4800",
      departmentOrUnit: "null",
      endOfYearBonus: "6,89",
    },
    {
      name: "Pataballa, Valli",
      hireDate: "abc",
      job: "Programmer",
      salary: null,
      departmentOrUnit: "60",
      endOfYearBonus: "1,62",
    },
    {
      name: "Lorentz, Diana",
      hireDate: "07-ARB-07",
      job: "Programmer",
      salary: "4200",
      departmentOrUnit: "60",
      endOfYearBonus: "13,17",
    },
    {
      name: "Greenberg, Nancy",
      hireDate: "17-AUG-02",
      job: "Manager",
      salary: "12008",
      departmentOrUnit: "100",
      endOfYearBonus: "74,69",
    },
    {
      name: "Faviet, Daniel",
      hireDate: "16-AUG-02",
      job: "Accountant",
      salary: "9000",
      departmentOrUnit: "100",
      endOfYearBonus: "2,92",
    },
    {
      name: "Chen, John",
      hireDate: "28-SEP-05",
      job: "Accountant",
      salary: "8200",
      departmentOrUnit: "100",
      endOfYearBonus: "9,31",
    },
    {
      name: "Sciarra, Ismael",
      hireDate: "30-SEP-05",
      job: "Accountant",
      salary: "7700",
      departmentOrUnit: "100",
      endOfYearBonus: "13,18",
    },
    {
      name: "Urman, Jose Manuel",
      hireDate: "07-MAR-06",
      job: "Accountant",
      salary: "7800",
      departmentOrUnit: "100",
      endOfYearBonus: "1,33",
    },
    {
      name: "Popp, Luis",
      hireDate: "07-DEC-07",
      job: "Accountant",
      salary: "6900",
      departmentOrUnit: "100",
      endOfYearBonus: "2,98",
    },
    {
      name: "Raphaely, Den",
      hireDate: "07-DEC-02",
      job: "Manager",
      salary: "11000",
      departmentOrUnit: "30",
      endOfYearBonus: "3,35",
    },
    {
      name: "Khoo, Alexander",
      hireDate: "18-MAY-03",
      job: "Clerk",
      salary: "3100",
      departmentOrUnit: "30",
      endOfYearBonus: "19,81",
    },
    {
      name: "Baida, Shelli",
      hireDate: "24-DEC-05",
      job: "Clerk",
      salary: "2900",
      departmentOrUnit: "30",
      endOfYearBonus: "11,06",
    },
    {
      name: "Tobias, Sigal",
      hireDate: "24-JUL-05",
      job: "NaN",
      salary: "2800",
      departmentOrUnit: null,
      endOfYearBonus: "undefined",
    },
    {
      name: "Himuro, Guy",
      hireDate: "15-NOV-05",
      job: "Clerk",
      salary: "2600",
      departmentOrUnit: "30",
      endOfYearBonus: "25,98",
    },
    {
      name: "Colmenares, Karen",
      hireDate: "10-AUG-07",
      job: "Clerk",
      salary: "2500",
      departmentOrUnit: "30",
      endOfYearBonus: "15,8",
    },
    {
      name: "Weiss, Matthew",
      hireDate: "18-JUL-04",
      job: "Manager",
      salary: "8000",
      departmentOrUnit: "50",
      endOfYearBonus: "25,17",
    },
    {
      name: "Fripp, Adam",
      hireDate: "10-APR-05",
      job: "Manager",
      salary: "8200",
      departmentOrUnit: "50",
      endOfYearBonus: "21",
    },
    {
      name: "Kaufling, Payam",
      hireDate: "01-MAY-03",
      job: "Manager",
      salary: "7900",
      departmentOrUnit: "undefined",
      endOfYearBonus: "21,33",
    },
    {
      name: "Vollman, Shanta",
      hireDate: "10-OCT-05",
      job: "null",
      salary: "6500",
      departmentOrUnit: "50",
      endOfYearBonus: "3,45",
    },
    {
      name: "Mourgos, Kevin",
      hireDate: "undefined",
      job: "Manager",
      salary: "5800",
      departmentOrUnit: "50",
      endOfYearBonus: "19,07",
    },
    {
      name: "Nayer, Julia",
      hireDate: "16-JUL-05",
      job: "Clerk",
      salary: "3200",
      departmentOrUnit: "50",
      endOfYearBonus: "18,7",
    },
    {
      name: "Mikkilineni, Irene",
      hireDate: "28-SEP-06",
      job: "Clerk",
      salary: "2700",
      departmentOrUnit: "50",
      endOfYearBonus: "11,82",
    },
    {
      name: "Landry, James",
      hireDate: "14-JAN-07",
      job: "Clerk",
      salary: "2400",
      departmentOrUnit: "50",
      endOfYearBonus: "NaN",
    },
    {
      name: "Markle, Steven",
      hireDate: "NaN",
      job: "Clerk",
      salary: "2200",
      departmentOrUnit: "50",
      endOfYearBonus: "11,26",
    },
    {
      name: "Bissot, Laura",
      hireDate: "20-AUG-05",
      job: "undefined",
      salary: "3300",
      departmentOrUnit: "50",
      endOfYearBonus: "4,53",
    },
    {
      name: "Atkinson, Mozhe",
      hireDate: "30-OCT-05",
      job: "Clerk",
      salary: "undefined",
      departmentOrUnit: "50",
      endOfYearBonus: "9,61",
    },
    {
      name: "Marlow, James",
      hireDate: "16-FEB-05",
      job: "Clerk",
      salary: "2500",
      departmentOrUnit: "50",
      endOfYearBonus: "15,74",
    },
    {
      name: "Olson, TJ",
      hireDate: "10-APR-07",
      job: "Clerk",
      salary: "2100",
      departmentOrUnit: "null",
      endOfYearBonus: "22,3",
    },
    {
      name: "undefined",
      hireDate: "14-JUN-04",
      job: "Clerk",
      salary: "3300",
      departmentOrUnit: "50",
      endOfYearBonus: "18,54",
    },
    {
      name: "Rogers, Michael",
      hireDate: "26-AUG-06",
      job: "Clerk",
      salary: "2900",
      departmentOrUnit: "50",
      endOfYearBonus: "null",
    },
    {
      name: "Gee, Ki",
      hireDate: "12-DEC-07",
      job: "NaN",
      salary: "2400",
      departmentOrUnit: "50",
      endOfYearBonus: "12,64",
    },
    {
      name: "Philtanker, Hazel",
      hireDate: "06-FEB-08",
      job: "Clerk",
      salary: "2200",
      departmentOrUnit: "NaN",
      endOfYearBonus: "24,17",
    },
    {
      name: "Ladwig, Renske",
      hireDate: "14-JUL-03",
      job: null,
      salary: "3600",
      departmentOrUnit: "50",
      endOfYearBonus: "17,86",
    },
    {
      name: "Stiles, Stephen",
      hireDate: "26-OCT-05",
      job: "Clerk",
      salary: "3200",
      departmentOrUnit: "50",
      endOfYearBonus: null,
    },
    {
      name: "Seo, John",
      hireDate: "12-FEB-06",
      job: "Clerk",
      salary: "2700",
      departmentOrUnit: "50",
      endOfYearBonus: "0,16",
    },
    {
      name: "Patel, Joshua",
      hireDate: "06-APR-06",
      job: "Clerk",
      salary: "2500",
      departmentOrUnit: "50",
      endOfYearBonus: "16,19",
    },
  ]);
});

Deno.test("should replace substings in one column", async () => {
  const table = sdb.newTable();
  await table.loadData(["test/data/files/employees.csv"]);
  await table.cleanColumnNames();

  await table.replace(["name", "endOfYearBonus"], { a: "@" });

  const data = await table.getData();

  assertEquals(data, [
    {
      name: "OConnell, Don@ld",
      hireDate: "21-JUN-07",
      job: "Clerk",
      salary: "2600",
      departmentOrUnit: "50",
      endOfYearBonus: "1,94%",
    },
    {
      name: "OConnell, Don@ld",
      hireDate: "21-JUN-07",
      job: "Clerk",
      salary: "2600",
      departmentOrUnit: "50",
      endOfYearBonus: "1,94%",
    },
    {
      name: "Gr@nt, Dougl@s",
      hireDate: "13-JAN-08",
      job: "Clerk",
      salary: "NaN",
      departmentOrUnit: "50",
      endOfYearBonus: "23,39%",
    },
    {
      name: null,
      hireDate: "17-SEP-03",
      job: "Assistant",
      salary: "4400",
      departmentOrUnit: "10",
      endOfYearBonus: "17,51%",
    },
    {
      name: "H@rtstein, Mich@el",
      hireDate: "17-FEB-04",
      job: "Manager",
      salary: "13000",
      departmentOrUnit: "20",
      endOfYearBonus: "2,71%",
    },
    {
      name: "F@y, P@t",
      hireDate: "17-AUG-05",
      job: "Representative",
      salary: "6000",
      departmentOrUnit: "20",
      endOfYearBonus: "18,68%",
    },
    {
      name: "M@vris, Sus@n",
      hireDate: "07-JUN-02",
      job: "Salesperson",
      salary: "6500",
      departmentOrUnit: "40",
      endOfYearBonus: "23,47%",
    },
    {
      name: "N@N",
      hireDate: "07-JUN-02",
      job: "Salesperson",
      salary: "10000",
      departmentOrUnit: "xyz",
      endOfYearBonus: "17,63%",
    },
    {
      name: "Higgins, Shelley",
      hireDate: "07-JUN-02",
      job: "Manager",
      salary: "12008",
      departmentOrUnit: "110",
      endOfYearBonus: "17,09%",
    },
    {
      name: "null",
      hireDate: "07-JUN-02",
      job: "Accountant",
      salary: "8300",
      departmentOrUnit: "110",
      endOfYearBonus: "15,7%",
    },
    {
      name: "King, Steven",
      hireDate: null,
      job: "President",
      salary: "24000",
      departmentOrUnit: "90",
      endOfYearBonus: "2,46%",
    },
    {
      name: "Kochh@r, Neen@",
      hireDate: "21-SEP-05",
      job: "Vice-president",
      salary: "&6%",
      departmentOrUnit: "90",
      endOfYearBonus: "11,6%",
    },
    {
      name: "De H@@n, Lex",
      hireDate: "null",
      job: "Vice-president",
      salary: "17000",
      departmentOrUnit: "90",
      endOfYearBonus: "23,43%",
    },
    {
      name: "Hunold, Alex@nder",
      hireDate: "03-JAN-06",
      job: "Programmer",
      salary: "9000",
      departmentOrUnit: "60",
      endOfYearBonus: "23,01%",
    },
    {
      name: "Ernst, Bruce",
      hireDate: "21-MAY-07",
      job: "Programmer",
      salary: "6000",
      departmentOrUnit: "60",
      endOfYearBonus: "25,91%",
    },
    {
      name: "Austin, D@vid",
      hireDate: "NaN",
      job: "Programmer",
      salary: "4800",
      departmentOrUnit: "null",
      endOfYearBonus: "6,89%",
    },
    {
      name: "P@t@b@ll@, V@lli",
      hireDate: "abc",
      job: "Programmer",
      salary: null,
      departmentOrUnit: "60",
      endOfYearBonus: "1,62%",
    },
    {
      name: "Lorentz, Di@n@",
      hireDate: "07-ARB-07",
      job: "Programmer",
      salary: "4200",
      departmentOrUnit: "60",
      endOfYearBonus: "13,17%",
    },
    {
      name: "Greenberg, N@ncy",
      hireDate: "17-AUG-02",
      job: "Manager",
      salary: "12008",
      departmentOrUnit: "100",
      endOfYearBonus: "74,69%",
    },
    {
      name: "F@viet, D@niel",
      hireDate: "16-AUG-02",
      job: "Accountant",
      salary: "9000",
      departmentOrUnit: "100",
      endOfYearBonus: "2,92%",
    },
    {
      name: "Chen, John",
      hireDate: "28-SEP-05",
      job: "Accountant",
      salary: "8200",
      departmentOrUnit: "100",
      endOfYearBonus: "9,31%",
    },
    {
      name: "Sci@rr@, Ism@el",
      hireDate: "30-SEP-05",
      job: "Accountant",
      salary: "7700",
      departmentOrUnit: "100",
      endOfYearBonus: "13,18%",
    },
    {
      name: "Urm@n, Jose M@nuel",
      hireDate: "07-MAR-06",
      job: "Accountant",
      salary: "7800",
      departmentOrUnit: "100",
      endOfYearBonus: "1,33%",
    },
    {
      name: "Popp, Luis",
      hireDate: "07-DEC-07",
      job: "Accountant",
      salary: "6900",
      departmentOrUnit: "100",
      endOfYearBonus: "2,98%",
    },
    {
      name: "R@ph@ely, Den",
      hireDate: "07-DEC-02",
      job: "Manager",
      salary: "11000",
      departmentOrUnit: "30",
      endOfYearBonus: "3,35%",
    },
    {
      name: "Khoo, Alex@nder",
      hireDate: "18-MAY-03",
      job: "Clerk",
      salary: "3100",
      departmentOrUnit: "30",
      endOfYearBonus: "19,81%",
    },
    {
      name: "B@id@, Shelli",
      hireDate: "24-DEC-05",
      job: "Clerk",
      salary: "2900",
      departmentOrUnit: "30",
      endOfYearBonus: "11,06%",
    },
    {
      name: "Tobi@s, Sig@l",
      hireDate: "24-JUL-05",
      job: "NaN",
      salary: "2800",
      departmentOrUnit: null,
      endOfYearBonus: "undefined",
    },
    {
      name: "Himuro, Guy",
      hireDate: "15-NOV-05",
      job: "Clerk",
      salary: "2600",
      departmentOrUnit: "30",
      endOfYearBonus: "25,98%",
    },
    {
      name: "Colmen@res, K@ren",
      hireDate: "10-AUG-07",
      job: "Clerk",
      salary: "2500",
      departmentOrUnit: "30",
      endOfYearBonus: "15,8%",
    },
    {
      name: "Weiss, M@tthew",
      hireDate: "18-JUL-04",
      job: "Manager",
      salary: "8000",
      departmentOrUnit: "50",
      endOfYearBonus: "25,17%",
    },
    {
      name: "Fripp, Ad@m",
      hireDate: "10-APR-05",
      job: "Manager",
      salary: "8200",
      departmentOrUnit: "50",
      endOfYearBonus: "21%",
    },
    {
      name: "K@ufling, P@y@m",
      hireDate: "01-MAY-03",
      job: "Manager",
      salary: "7900",
      departmentOrUnit: "undefined",
      endOfYearBonus: "21,33%",
    },
    {
      name: "Vollm@n, Sh@nt@",
      hireDate: "10-OCT-05",
      job: "null",
      salary: "6500",
      departmentOrUnit: "50",
      endOfYearBonus: "3,45%",
    },
    {
      name: "Mourgos, Kevin",
      hireDate: "undefined",
      job: "Manager",
      salary: "5800",
      departmentOrUnit: "50",
      endOfYearBonus: "19,07%",
    },
    {
      name: "N@yer, Juli@",
      hireDate: "16-JUL-05",
      job: "Clerk",
      salary: "3200",
      departmentOrUnit: "50",
      endOfYearBonus: "18,7%",
    },
    {
      name: "Mikkilineni, Irene",
      hireDate: "28-SEP-06",
      job: "Clerk",
      salary: "2700",
      departmentOrUnit: "50",
      endOfYearBonus: "11,82%",
    },
    {
      name: "L@ndry, J@mes",
      hireDate: "14-JAN-07",
      job: "Clerk",
      salary: "2400",
      departmentOrUnit: "50",
      endOfYearBonus: "N@N",
    },
    {
      name: "M@rkle, Steven",
      hireDate: "NaN",
      job: "Clerk",
      salary: "2200",
      departmentOrUnit: "50",
      endOfYearBonus: "11,26%",
    },
    {
      name: "Bissot, L@ur@",
      hireDate: "20-AUG-05",
      job: "undefined",
      salary: "3300",
      departmentOrUnit: "50",
      endOfYearBonus: "4,53%",
    },
    {
      name: "Atkinson, Mozhe",
      hireDate: "30-OCT-05",
      job: "Clerk",
      salary: "undefined",
      departmentOrUnit: "50",
      endOfYearBonus: "9,61%",
    },
    {
      name: "M@rlow, J@mes",
      hireDate: "16-FEB-05",
      job: "Clerk",
      salary: "2500",
      departmentOrUnit: "50",
      endOfYearBonus: "15,74%",
    },
    {
      name: "Olson, TJ",
      hireDate: "10-APR-07",
      job: "Clerk",
      salary: "2100",
      departmentOrUnit: "null",
      endOfYearBonus: "22,3%",
    },
    {
      name: "undefined",
      hireDate: "14-JUN-04",
      job: "Clerk",
      salary: "3300",
      departmentOrUnit: "50",
      endOfYearBonus: "18,54%",
    },
    {
      name: "Rogers, Mich@el",
      hireDate: "26-AUG-06",
      job: "Clerk",
      salary: "2900",
      departmentOrUnit: "50",
      endOfYearBonus: "null",
    },
    {
      name: "Gee, Ki",
      hireDate: "12-DEC-07",
      job: "NaN",
      salary: "2400",
      departmentOrUnit: "50",
      endOfYearBonus: "12,64%",
    },
    {
      name: "Philt@nker, H@zel",
      hireDate: "06-FEB-08",
      job: "Clerk",
      salary: "2200",
      departmentOrUnit: "NaN",
      endOfYearBonus: "24,17%",
    },
    {
      name: "L@dwig, Renske",
      hireDate: "14-JUL-03",
      job: null,
      salary: "3600",
      departmentOrUnit: "50",
      endOfYearBonus: "17,86%",
    },
    {
      name: "Stiles, Stephen",
      hireDate: "26-OCT-05",
      job: "Clerk",
      salary: "3200",
      departmentOrUnit: "50",
      endOfYearBonus: null,
    },
    {
      name: "Seo, John",
      hireDate: "12-FEB-06",
      job: "Clerk",
      salary: "2700",
      departmentOrUnit: "50",
      endOfYearBonus: "0,16%",
    },
    {
      name: "P@tel, Joshu@",
      hireDate: "06-APR-06",
      job: "Clerk",
      salary: "2500",
      departmentOrUnit: "50",
      endOfYearBonus: "16,19%",
    },
  ]);
});

Deno.test("should replace entire strings in one column", async () => {
  const table = sdb.newTable();
  await table.loadData(["test/data/files/employees.csv"]);
  await table.cleanColumnNames();

  await table.replace(
    ["name", "endOfYearBonus"],
    { "Grant, Douglas": "BOSS" },
    { entireString: true },
  );

  const data = await table.getData();

  assertEquals(data, [
    {
      name: "OConnell, Donald",
      hireDate: "21-JUN-07",
      job: "Clerk",
      salary: "2600",
      departmentOrUnit: "50",
      endOfYearBonus: "1,94%",
    },
    {
      name: "OConnell, Donald",
      hireDate: "21-JUN-07",
      job: "Clerk",
      salary: "2600",
      departmentOrUnit: "50",
      endOfYearBonus: "1,94%",
    },
    {
      name: "BOSS",
      hireDate: "13-JAN-08",
      job: "Clerk",
      salary: "NaN",
      departmentOrUnit: "50",
      endOfYearBonus: "23,39%",
    },
    {
      name: null,
      hireDate: "17-SEP-03",
      job: "Assistant",
      salary: "4400",
      departmentOrUnit: "10",
      endOfYearBonus: "17,51%",
    },
    {
      name: "Hartstein, Michael",
      hireDate: "17-FEB-04",
      job: "Manager",
      salary: "13000",
      departmentOrUnit: "20",
      endOfYearBonus: "2,71%",
    },
    {
      name: "Fay, Pat",
      hireDate: "17-AUG-05",
      job: "Representative",
      salary: "6000",
      departmentOrUnit: "20",
      endOfYearBonus: "18,68%",
    },
    {
      name: "Mavris, Susan",
      hireDate: "07-JUN-02",
      job: "Salesperson",
      salary: "6500",
      departmentOrUnit: "40",
      endOfYearBonus: "23,47%",
    },
    {
      name: "NaN",
      hireDate: "07-JUN-02",
      job: "Salesperson",
      salary: "10000",
      departmentOrUnit: "xyz",
      endOfYearBonus: "17,63%",
    },
    {
      name: "Higgins, Shelley",
      hireDate: "07-JUN-02",
      job: "Manager",
      salary: "12008",
      departmentOrUnit: "110",
      endOfYearBonus: "17,09%",
    },
    {
      name: "null",
      hireDate: "07-JUN-02",
      job: "Accountant",
      salary: "8300",
      departmentOrUnit: "110",
      endOfYearBonus: "15,7%",
    },
    {
      name: "King, Steven",
      hireDate: null,
      job: "President",
      salary: "24000",
      departmentOrUnit: "90",
      endOfYearBonus: "2,46%",
    },
    {
      name: "Kochhar, Neena",
      hireDate: "21-SEP-05",
      job: "Vice-president",
      salary: "&6%",
      departmentOrUnit: "90",
      endOfYearBonus: "11,6%",
    },
    {
      name: "De Haan, Lex",
      hireDate: "null",
      job: "Vice-president",
      salary: "17000",
      departmentOrUnit: "90",
      endOfYearBonus: "23,43%",
    },
    {
      name: "Hunold, Alexander",
      hireDate: "03-JAN-06",
      job: "Programmer",
      salary: "9000",
      departmentOrUnit: "60",
      endOfYearBonus: "23,01%",
    },
    {
      name: "Ernst, Bruce",
      hireDate: "21-MAY-07",
      job: "Programmer",
      salary: "6000",
      departmentOrUnit: "60",
      endOfYearBonus: "25,91%",
    },
    {
      name: "Austin, David",
      hireDate: "NaN",
      job: "Programmer",
      salary: "4800",
      departmentOrUnit: "null",
      endOfYearBonus: "6,89%",
    },
    {
      name: "Pataballa, Valli",
      hireDate: "abc",
      job: "Programmer",
      salary: null,
      departmentOrUnit: "60",
      endOfYearBonus: "1,62%",
    },
    {
      name: "Lorentz, Diana",
      hireDate: "07-ARB-07",
      job: "Programmer",
      salary: "4200",
      departmentOrUnit: "60",
      endOfYearBonus: "13,17%",
    },
    {
      name: "Greenberg, Nancy",
      hireDate: "17-AUG-02",
      job: "Manager",
      salary: "12008",
      departmentOrUnit: "100",
      endOfYearBonus: "74,69%",
    },
    {
      name: "Faviet, Daniel",
      hireDate: "16-AUG-02",
      job: "Accountant",
      salary: "9000",
      departmentOrUnit: "100",
      endOfYearBonus: "2,92%",
    },
    {
      name: "Chen, John",
      hireDate: "28-SEP-05",
      job: "Accountant",
      salary: "8200",
      departmentOrUnit: "100",
      endOfYearBonus: "9,31%",
    },
    {
      name: "Sciarra, Ismael",
      hireDate: "30-SEP-05",
      job: "Accountant",
      salary: "7700",
      departmentOrUnit: "100",
      endOfYearBonus: "13,18%",
    },
    {
      name: "Urman, Jose Manuel",
      hireDate: "07-MAR-06",
      job: "Accountant",
      salary: "7800",
      departmentOrUnit: "100",
      endOfYearBonus: "1,33%",
    },
    {
      name: "Popp, Luis",
      hireDate: "07-DEC-07",
      job: "Accountant",
      salary: "6900",
      departmentOrUnit: "100",
      endOfYearBonus: "2,98%",
    },
    {
      name: "Raphaely, Den",
      hireDate: "07-DEC-02",
      job: "Manager",
      salary: "11000",
      departmentOrUnit: "30",
      endOfYearBonus: "3,35%",
    },
    {
      name: "Khoo, Alexander",
      hireDate: "18-MAY-03",
      job: "Clerk",
      salary: "3100",
      departmentOrUnit: "30",
      endOfYearBonus: "19,81%",
    },
    {
      name: "Baida, Shelli",
      hireDate: "24-DEC-05",
      job: "Clerk",
      salary: "2900",
      departmentOrUnit: "30",
      endOfYearBonus: "11,06%",
    },
    {
      name: "Tobias, Sigal",
      hireDate: "24-JUL-05",
      job: "NaN",
      salary: "2800",
      departmentOrUnit: null,
      endOfYearBonus: "undefined",
    },
    {
      name: "Himuro, Guy",
      hireDate: "15-NOV-05",
      job: "Clerk",
      salary: "2600",
      departmentOrUnit: "30",
      endOfYearBonus: "25,98%",
    },
    {
      name: "Colmenares, Karen",
      hireDate: "10-AUG-07",
      job: "Clerk",
      salary: "2500",
      departmentOrUnit: "30",
      endOfYearBonus: "15,8%",
    },
    {
      name: "Weiss, Matthew",
      hireDate: "18-JUL-04",
      job: "Manager",
      salary: "8000",
      departmentOrUnit: "50",
      endOfYearBonus: "25,17%",
    },
    {
      name: "Fripp, Adam",
      hireDate: "10-APR-05",
      job: "Manager",
      salary: "8200",
      departmentOrUnit: "50",
      endOfYearBonus: "21%",
    },
    {
      name: "Kaufling, Payam",
      hireDate: "01-MAY-03",
      job: "Manager",
      salary: "7900",
      departmentOrUnit: "undefined",
      endOfYearBonus: "21,33%",
    },
    {
      name: "Vollman, Shanta",
      hireDate: "10-OCT-05",
      job: "null",
      salary: "6500",
      departmentOrUnit: "50",
      endOfYearBonus: "3,45%",
    },
    {
      name: "Mourgos, Kevin",
      hireDate: "undefined",
      job: "Manager",
      salary: "5800",
      departmentOrUnit: "50",
      endOfYearBonus: "19,07%",
    },
    {
      name: "Nayer, Julia",
      hireDate: "16-JUL-05",
      job: "Clerk",
      salary: "3200",
      departmentOrUnit: "50",
      endOfYearBonus: "18,7%",
    },
    {
      name: "Mikkilineni, Irene",
      hireDate: "28-SEP-06",
      job: "Clerk",
      salary: "2700",
      departmentOrUnit: "50",
      endOfYearBonus: "11,82%",
    },
    {
      name: "Landry, James",
      hireDate: "14-JAN-07",
      job: "Clerk",
      salary: "2400",
      departmentOrUnit: "50",
      endOfYearBonus: "NaN",
    },
    {
      name: "Markle, Steven",
      hireDate: "NaN",
      job: "Clerk",
      salary: "2200",
      departmentOrUnit: "50",
      endOfYearBonus: "11,26%",
    },
    {
      name: "Bissot, Laura",
      hireDate: "20-AUG-05",
      job: "undefined",
      salary: "3300",
      departmentOrUnit: "50",
      endOfYearBonus: "4,53%",
    },
    {
      name: "Atkinson, Mozhe",
      hireDate: "30-OCT-05",
      job: "Clerk",
      salary: "undefined",
      departmentOrUnit: "50",
      endOfYearBonus: "9,61%",
    },
    {
      name: "Marlow, James",
      hireDate: "16-FEB-05",
      job: "Clerk",
      salary: "2500",
      departmentOrUnit: "50",
      endOfYearBonus: "15,74%",
    },
    {
      name: "Olson, TJ",
      hireDate: "10-APR-07",
      job: "Clerk",
      salary: "2100",
      departmentOrUnit: "null",
      endOfYearBonus: "22,3%",
    },
    {
      name: "undefined",
      hireDate: "14-JUN-04",
      job: "Clerk",
      salary: "3300",
      departmentOrUnit: "50",
      endOfYearBonus: "18,54%",
    },
    {
      name: "Rogers, Michael",
      hireDate: "26-AUG-06",
      job: "Clerk",
      salary: "2900",
      departmentOrUnit: "50",
      endOfYearBonus: "null",
    },
    {
      name: "Gee, Ki",
      hireDate: "12-DEC-07",
      job: "NaN",
      salary: "2400",
      departmentOrUnit: "50",
      endOfYearBonus: "12,64%",
    },
    {
      name: "Philtanker, Hazel",
      hireDate: "06-FEB-08",
      job: "Clerk",
      salary: "2200",
      departmentOrUnit: "NaN",
      endOfYearBonus: "24,17%",
    },
    {
      name: "Ladwig, Renske",
      hireDate: "14-JUL-03",
      job: null,
      salary: "3600",
      departmentOrUnit: "50",
      endOfYearBonus: "17,86%",
    },
    {
      name: "Stiles, Stephen",
      hireDate: "26-OCT-05",
      job: "Clerk",
      salary: "3200",
      departmentOrUnit: "50",
      endOfYearBonus: null,
    },
    {
      name: "Seo, John",
      hireDate: "12-FEB-06",
      job: "Clerk",
      salary: "2700",
      departmentOrUnit: "50",
      endOfYearBonus: "0,16%",
    },
    {
      name: "Patel, Joshua",
      hireDate: "06-APR-06",
      job: "Clerk",
      salary: "2500",
      departmentOrUnit: "50",
      endOfYearBonus: "16,19%",
    },
  ]);
});

Deno.test("should replace multiple texts in one column", async () => {
  const table = sdb.newTable();
  await table.loadData(["test/data/files/employees.csv"]);
  await table.cleanColumnNames();

  await table.replace(["endOfYearBonus"], { "%": "", ",": "." });

  const data = await table.getData();

  assertEquals(data, [
    {
      name: "OConnell, Donald",
      hireDate: "21-JUN-07",
      job: "Clerk",
      salary: "2600",
      departmentOrUnit: "50",
      endOfYearBonus: "1.94",
    },
    {
      name: "OConnell, Donald",
      hireDate: "21-JUN-07",
      job: "Clerk",
      salary: "2600",
      departmentOrUnit: "50",
      endOfYearBonus: "1.94",
    },
    {
      name: "Grant, Douglas",
      hireDate: "13-JAN-08",
      job: "Clerk",
      salary: "NaN",
      departmentOrUnit: "50",
      endOfYearBonus: "23.39",
    },
    {
      name: null,
      hireDate: "17-SEP-03",
      job: "Assistant",
      salary: "4400",
      departmentOrUnit: "10",
      endOfYearBonus: "17.51",
    },
    {
      name: "Hartstein, Michael",
      hireDate: "17-FEB-04",
      job: "Manager",
      salary: "13000",
      departmentOrUnit: "20",
      endOfYearBonus: "2.71",
    },
    {
      name: "Fay, Pat",
      hireDate: "17-AUG-05",
      job: "Representative",
      salary: "6000",
      departmentOrUnit: "20",
      endOfYearBonus: "18.68",
    },
    {
      name: "Mavris, Susan",
      hireDate: "07-JUN-02",
      job: "Salesperson",
      salary: "6500",
      departmentOrUnit: "40",
      endOfYearBonus: "23.47",
    },
    {
      name: "NaN",
      hireDate: "07-JUN-02",
      job: "Salesperson",
      salary: "10000",
      departmentOrUnit: "xyz",
      endOfYearBonus: "17.63",
    },
    {
      name: "Higgins, Shelley",
      hireDate: "07-JUN-02",
      job: "Manager",
      salary: "12008",
      departmentOrUnit: "110",
      endOfYearBonus: "17.09",
    },
    {
      name: "null",
      hireDate: "07-JUN-02",
      job: "Accountant",
      salary: "8300",
      departmentOrUnit: "110",
      endOfYearBonus: "15.7",
    },
    {
      name: "King, Steven",
      hireDate: null,
      job: "President",
      salary: "24000",
      departmentOrUnit: "90",
      endOfYearBonus: "2.46",
    },
    {
      name: "Kochhar, Neena",
      hireDate: "21-SEP-05",
      job: "Vice-president",
      salary: "&6%",
      departmentOrUnit: "90",
      endOfYearBonus: "11.6",
    },
    {
      name: "De Haan, Lex",
      hireDate: "null",
      job: "Vice-president",
      salary: "17000",
      departmentOrUnit: "90",
      endOfYearBonus: "23.43",
    },
    {
      name: "Hunold, Alexander",
      hireDate: "03-JAN-06",
      job: "Programmer",
      salary: "9000",
      departmentOrUnit: "60",
      endOfYearBonus: "23.01",
    },
    {
      name: "Ernst, Bruce",
      hireDate: "21-MAY-07",
      job: "Programmer",
      salary: "6000",
      departmentOrUnit: "60",
      endOfYearBonus: "25.91",
    },
    {
      name: "Austin, David",
      hireDate: "NaN",
      job: "Programmer",
      salary: "4800",
      departmentOrUnit: "null",
      endOfYearBonus: "6.89",
    },
    {
      name: "Pataballa, Valli",
      hireDate: "abc",
      job: "Programmer",
      salary: null,
      departmentOrUnit: "60",
      endOfYearBonus: "1.62",
    },
    {
      name: "Lorentz, Diana",
      hireDate: "07-ARB-07",
      job: "Programmer",
      salary: "4200",
      departmentOrUnit: "60",
      endOfYearBonus: "13.17",
    },
    {
      name: "Greenberg, Nancy",
      hireDate: "17-AUG-02",
      job: "Manager",
      salary: "12008",
      departmentOrUnit: "100",
      endOfYearBonus: "74.69",
    },
    {
      name: "Faviet, Daniel",
      hireDate: "16-AUG-02",
      job: "Accountant",
      salary: "9000",
      departmentOrUnit: "100",
      endOfYearBonus: "2.92",
    },
    {
      name: "Chen, John",
      hireDate: "28-SEP-05",
      job: "Accountant",
      salary: "8200",
      departmentOrUnit: "100",
      endOfYearBonus: "9.31",
    },
    {
      name: "Sciarra, Ismael",
      hireDate: "30-SEP-05",
      job: "Accountant",
      salary: "7700",
      departmentOrUnit: "100",
      endOfYearBonus: "13.18",
    },
    {
      name: "Urman, Jose Manuel",
      hireDate: "07-MAR-06",
      job: "Accountant",
      salary: "7800",
      departmentOrUnit: "100",
      endOfYearBonus: "1.33",
    },
    {
      name: "Popp, Luis",
      hireDate: "07-DEC-07",
      job: "Accountant",
      salary: "6900",
      departmentOrUnit: "100",
      endOfYearBonus: "2.98",
    },
    {
      name: "Raphaely, Den",
      hireDate: "07-DEC-02",
      job: "Manager",
      salary: "11000",
      departmentOrUnit: "30",
      endOfYearBonus: "3.35",
    },
    {
      name: "Khoo, Alexander",
      hireDate: "18-MAY-03",
      job: "Clerk",
      salary: "3100",
      departmentOrUnit: "30",
      endOfYearBonus: "19.81",
    },
    {
      name: "Baida, Shelli",
      hireDate: "24-DEC-05",
      job: "Clerk",
      salary: "2900",
      departmentOrUnit: "30",
      endOfYearBonus: "11.06",
    },
    {
      name: "Tobias, Sigal",
      hireDate: "24-JUL-05",
      job: "NaN",
      salary: "2800",
      departmentOrUnit: null,
      endOfYearBonus: "undefined",
    },
    {
      name: "Himuro, Guy",
      hireDate: "15-NOV-05",
      job: "Clerk",
      salary: "2600",
      departmentOrUnit: "30",
      endOfYearBonus: "25.98",
    },
    {
      name: "Colmenares, Karen",
      hireDate: "10-AUG-07",
      job: "Clerk",
      salary: "2500",
      departmentOrUnit: "30",
      endOfYearBonus: "15.8",
    },
    {
      name: "Weiss, Matthew",
      hireDate: "18-JUL-04",
      job: "Manager",
      salary: "8000",
      departmentOrUnit: "50",
      endOfYearBonus: "25.17",
    },
    {
      name: "Fripp, Adam",
      hireDate: "10-APR-05",
      job: "Manager",
      salary: "8200",
      departmentOrUnit: "50",
      endOfYearBonus: "21",
    },
    {
      name: "Kaufling, Payam",
      hireDate: "01-MAY-03",
      job: "Manager",
      salary: "7900",
      departmentOrUnit: "undefined",
      endOfYearBonus: "21.33",
    },
    {
      name: "Vollman, Shanta",
      hireDate: "10-OCT-05",
      job: "null",
      salary: "6500",
      departmentOrUnit: "50",
      endOfYearBonus: "3.45",
    },
    {
      name: "Mourgos, Kevin",
      hireDate: "undefined",
      job: "Manager",
      salary: "5800",
      departmentOrUnit: "50",
      endOfYearBonus: "19.07",
    },
    {
      name: "Nayer, Julia",
      hireDate: "16-JUL-05",
      job: "Clerk",
      salary: "3200",
      departmentOrUnit: "50",
      endOfYearBonus: "18.7",
    },
    {
      name: "Mikkilineni, Irene",
      hireDate: "28-SEP-06",
      job: "Clerk",
      salary: "2700",
      departmentOrUnit: "50",
      endOfYearBonus: "11.82",
    },
    {
      name: "Landry, James",
      hireDate: "14-JAN-07",
      job: "Clerk",
      salary: "2400",
      departmentOrUnit: "50",
      endOfYearBonus: "NaN",
    },
    {
      name: "Markle, Steven",
      hireDate: "NaN",
      job: "Clerk",
      salary: "2200",
      departmentOrUnit: "50",
      endOfYearBonus: "11.26",
    },
    {
      name: "Bissot, Laura",
      hireDate: "20-AUG-05",
      job: "undefined",
      salary: "3300",
      departmentOrUnit: "50",
      endOfYearBonus: "4.53",
    },
    {
      name: "Atkinson, Mozhe",
      hireDate: "30-OCT-05",
      job: "Clerk",
      salary: "undefined",
      departmentOrUnit: "50",
      endOfYearBonus: "9.61",
    },
    {
      name: "Marlow, James",
      hireDate: "16-FEB-05",
      job: "Clerk",
      salary: "2500",
      departmentOrUnit: "50",
      endOfYearBonus: "15.74",
    },
    {
      name: "Olson, TJ",
      hireDate: "10-APR-07",
      job: "Clerk",
      salary: "2100",
      departmentOrUnit: "null",
      endOfYearBonus: "22.3",
    },
    {
      name: "undefined",
      hireDate: "14-JUN-04",
      job: "Clerk",
      salary: "3300",
      departmentOrUnit: "50",
      endOfYearBonus: "18.54",
    },
    {
      name: "Rogers, Michael",
      hireDate: "26-AUG-06",
      job: "Clerk",
      salary: "2900",
      departmentOrUnit: "50",
      endOfYearBonus: "null",
    },
    {
      name: "Gee, Ki",
      hireDate: "12-DEC-07",
      job: "NaN",
      salary: "2400",
      departmentOrUnit: "50",
      endOfYearBonus: "12.64",
    },
    {
      name: "Philtanker, Hazel",
      hireDate: "06-FEB-08",
      job: "Clerk",
      salary: "2200",
      departmentOrUnit: "NaN",
      endOfYearBonus: "24.17",
    },
    {
      name: "Ladwig, Renske",
      hireDate: "14-JUL-03",
      job: null,
      salary: "3600",
      departmentOrUnit: "50",
      endOfYearBonus: "17.86",
    },
    {
      name: "Stiles, Stephen",
      hireDate: "26-OCT-05",
      job: "Clerk",
      salary: "3200",
      departmentOrUnit: "50",
      endOfYearBonus: null,
    },
    {
      name: "Seo, John",
      hireDate: "12-FEB-06",
      job: "Clerk",
      salary: "2700",
      departmentOrUnit: "50",
      endOfYearBonus: "0.16",
    },
    {
      name: "Patel, Joshua",
      hireDate: "06-APR-06",
      job: "Clerk",
      salary: "2500",
      departmentOrUnit: "50",
      endOfYearBonus: "16.19",
    },
  ]);
});

Deno.test("should replace the text in multiple columns", async () => {
  const table = sdb.newTable();
  await table.loadData(["test/data/files/employees.csv"]);
  await table.cleanColumnNames();

  await table.replace(["name", "endOfYearBonus"], { ",": " => " });

  const data = await table.getData();

  assertEquals(data, [
    {
      name: "OConnell =>  Donald",
      hireDate: "21-JUN-07",
      job: "Clerk",
      salary: "2600",
      departmentOrUnit: "50",
      endOfYearBonus: "1 => 94%",
    },
    {
      name: "OConnell =>  Donald",
      hireDate: "21-JUN-07",
      job: "Clerk",
      salary: "2600",
      departmentOrUnit: "50",
      endOfYearBonus: "1 => 94%",
    },
    {
      name: "Grant =>  Douglas",
      hireDate: "13-JAN-08",
      job: "Clerk",
      salary: "NaN",
      departmentOrUnit: "50",
      endOfYearBonus: "23 => 39%",
    },
    {
      name: null,
      hireDate: "17-SEP-03",
      job: "Assistant",
      salary: "4400",
      departmentOrUnit: "10",
      endOfYearBonus: "17 => 51%",
    },
    {
      name: "Hartstein =>  Michael",
      hireDate: "17-FEB-04",
      job: "Manager",
      salary: "13000",
      departmentOrUnit: "20",
      endOfYearBonus: "2 => 71%",
    },
    {
      name: "Fay =>  Pat",
      hireDate: "17-AUG-05",
      job: "Representative",
      salary: "6000",
      departmentOrUnit: "20",
      endOfYearBonus: "18 => 68%",
    },
    {
      name: "Mavris =>  Susan",
      hireDate: "07-JUN-02",
      job: "Salesperson",
      salary: "6500",
      departmentOrUnit: "40",
      endOfYearBonus: "23 => 47%",
    },
    {
      name: "NaN",
      hireDate: "07-JUN-02",
      job: "Salesperson",
      salary: "10000",
      departmentOrUnit: "xyz",
      endOfYearBonus: "17 => 63%",
    },
    {
      name: "Higgins =>  Shelley",
      hireDate: "07-JUN-02",
      job: "Manager",
      salary: "12008",
      departmentOrUnit: "110",
      endOfYearBonus: "17 => 09%",
    },
    {
      name: "null",
      hireDate: "07-JUN-02",
      job: "Accountant",
      salary: "8300",
      departmentOrUnit: "110",
      endOfYearBonus: "15 => 7%",
    },
    {
      name: "King =>  Steven",
      hireDate: null,
      job: "President",
      salary: "24000",
      departmentOrUnit: "90",
      endOfYearBonus: "2 => 46%",
    },
    {
      name: "Kochhar =>  Neena",
      hireDate: "21-SEP-05",
      job: "Vice-president",
      salary: "&6%",
      departmentOrUnit: "90",
      endOfYearBonus: "11 => 6%",
    },
    {
      name: "De Haan =>  Lex",
      hireDate: "null",
      job: "Vice-president",
      salary: "17000",
      departmentOrUnit: "90",
      endOfYearBonus: "23 => 43%",
    },
    {
      name: "Hunold =>  Alexander",
      hireDate: "03-JAN-06",
      job: "Programmer",
      salary: "9000",
      departmentOrUnit: "60",
      endOfYearBonus: "23 => 01%",
    },
    {
      name: "Ernst =>  Bruce",
      hireDate: "21-MAY-07",
      job: "Programmer",
      salary: "6000",
      departmentOrUnit: "60",
      endOfYearBonus: "25 => 91%",
    },
    {
      name: "Austin =>  David",
      hireDate: "NaN",
      job: "Programmer",
      salary: "4800",
      departmentOrUnit: "null",
      endOfYearBonus: "6 => 89%",
    },
    {
      name: "Pataballa =>  Valli",
      hireDate: "abc",
      job: "Programmer",
      salary: null,
      departmentOrUnit: "60",
      endOfYearBonus: "1 => 62%",
    },
    {
      name: "Lorentz =>  Diana",
      hireDate: "07-ARB-07",
      job: "Programmer",
      salary: "4200",
      departmentOrUnit: "60",
      endOfYearBonus: "13 => 17%",
    },
    {
      name: "Greenberg =>  Nancy",
      hireDate: "17-AUG-02",
      job: "Manager",
      salary: "12008",
      departmentOrUnit: "100",
      endOfYearBonus: "74 => 69%",
    },
    {
      name: "Faviet =>  Daniel",
      hireDate: "16-AUG-02",
      job: "Accountant",
      salary: "9000",
      departmentOrUnit: "100",
      endOfYearBonus: "2 => 92%",
    },
    {
      name: "Chen =>  John",
      hireDate: "28-SEP-05",
      job: "Accountant",
      salary: "8200",
      departmentOrUnit: "100",
      endOfYearBonus: "9 => 31%",
    },
    {
      name: "Sciarra =>  Ismael",
      hireDate: "30-SEP-05",
      job: "Accountant",
      salary: "7700",
      departmentOrUnit: "100",
      endOfYearBonus: "13 => 18%",
    },
    {
      name: "Urman =>  Jose Manuel",
      hireDate: "07-MAR-06",
      job: "Accountant",
      salary: "7800",
      departmentOrUnit: "100",
      endOfYearBonus: "1 => 33%",
    },
    {
      name: "Popp =>  Luis",
      hireDate: "07-DEC-07",
      job: "Accountant",
      salary: "6900",
      departmentOrUnit: "100",
      endOfYearBonus: "2 => 98%",
    },
    {
      name: "Raphaely =>  Den",
      hireDate: "07-DEC-02",
      job: "Manager",
      salary: "11000",
      departmentOrUnit: "30",
      endOfYearBonus: "3 => 35%",
    },
    {
      name: "Khoo =>  Alexander",
      hireDate: "18-MAY-03",
      job: "Clerk",
      salary: "3100",
      departmentOrUnit: "30",
      endOfYearBonus: "19 => 81%",
    },
    {
      name: "Baida =>  Shelli",
      hireDate: "24-DEC-05",
      job: "Clerk",
      salary: "2900",
      departmentOrUnit: "30",
      endOfYearBonus: "11 => 06%",
    },
    {
      name: "Tobias =>  Sigal",
      hireDate: "24-JUL-05",
      job: "NaN",
      salary: "2800",
      departmentOrUnit: null,
      endOfYearBonus: "undefined",
    },
    {
      name: "Himuro =>  Guy",
      hireDate: "15-NOV-05",
      job: "Clerk",
      salary: "2600",
      departmentOrUnit: "30",
      endOfYearBonus: "25 => 98%",
    },
    {
      name: "Colmenares =>  Karen",
      hireDate: "10-AUG-07",
      job: "Clerk",
      salary: "2500",
      departmentOrUnit: "30",
      endOfYearBonus: "15 => 8%",
    },
    {
      name: "Weiss =>  Matthew",
      hireDate: "18-JUL-04",
      job: "Manager",
      salary: "8000",
      departmentOrUnit: "50",
      endOfYearBonus: "25 => 17%",
    },
    {
      name: "Fripp =>  Adam",
      hireDate: "10-APR-05",
      job: "Manager",
      salary: "8200",
      departmentOrUnit: "50",
      endOfYearBonus: "21%",
    },
    {
      name: "Kaufling =>  Payam",
      hireDate: "01-MAY-03",
      job: "Manager",
      salary: "7900",
      departmentOrUnit: "undefined",
      endOfYearBonus: "21 => 33%",
    },
    {
      name: "Vollman =>  Shanta",
      hireDate: "10-OCT-05",
      job: "null",
      salary: "6500",
      departmentOrUnit: "50",
      endOfYearBonus: "3 => 45%",
    },
    {
      name: "Mourgos =>  Kevin",
      hireDate: "undefined",
      job: "Manager",
      salary: "5800",
      departmentOrUnit: "50",
      endOfYearBonus: "19 => 07%",
    },
    {
      name: "Nayer =>  Julia",
      hireDate: "16-JUL-05",
      job: "Clerk",
      salary: "3200",
      departmentOrUnit: "50",
      endOfYearBonus: "18 => 7%",
    },
    {
      name: "Mikkilineni =>  Irene",
      hireDate: "28-SEP-06",
      job: "Clerk",
      salary: "2700",
      departmentOrUnit: "50",
      endOfYearBonus: "11 => 82%",
    },
    {
      name: "Landry =>  James",
      hireDate: "14-JAN-07",
      job: "Clerk",
      salary: "2400",
      departmentOrUnit: "50",
      endOfYearBonus: "NaN",
    },
    {
      name: "Markle =>  Steven",
      hireDate: "NaN",
      job: "Clerk",
      salary: "2200",
      departmentOrUnit: "50",
      endOfYearBonus: "11 => 26%",
    },
    {
      name: "Bissot =>  Laura",
      hireDate: "20-AUG-05",
      job: "undefined",
      salary: "3300",
      departmentOrUnit: "50",
      endOfYearBonus: "4 => 53%",
    },
    {
      name: "Atkinson =>  Mozhe",
      hireDate: "30-OCT-05",
      job: "Clerk",
      salary: "undefined",
      departmentOrUnit: "50",
      endOfYearBonus: "9 => 61%",
    },
    {
      name: "Marlow =>  James",
      hireDate: "16-FEB-05",
      job: "Clerk",
      salary: "2500",
      departmentOrUnit: "50",
      endOfYearBonus: "15 => 74%",
    },
    {
      name: "Olson =>  TJ",
      hireDate: "10-APR-07",
      job: "Clerk",
      salary: "2100",
      departmentOrUnit: "null",
      endOfYearBonus: "22 => 3%",
    },
    {
      name: "undefined",
      hireDate: "14-JUN-04",
      job: "Clerk",
      salary: "3300",
      departmentOrUnit: "50",
      endOfYearBonus: "18 => 54%",
    },
    {
      name: "Rogers =>  Michael",
      hireDate: "26-AUG-06",
      job: "Clerk",
      salary: "2900",
      departmentOrUnit: "50",
      endOfYearBonus: "null",
    },
    {
      name: "Gee =>  Ki",
      hireDate: "12-DEC-07",
      job: "NaN",
      salary: "2400",
      departmentOrUnit: "50",
      endOfYearBonus: "12 => 64%",
    },
    {
      name: "Philtanker =>  Hazel",
      hireDate: "06-FEB-08",
      job: "Clerk",
      salary: "2200",
      departmentOrUnit: "NaN",
      endOfYearBonus: "24 => 17%",
    },
    {
      name: "Ladwig =>  Renske",
      hireDate: "14-JUL-03",
      job: null,
      salary: "3600",
      departmentOrUnit: "50",
      endOfYearBonus: "17 => 86%",
    },
    {
      name: "Stiles =>  Stephen",
      hireDate: "26-OCT-05",
      job: "Clerk",
      salary: "3200",
      departmentOrUnit: "50",
      endOfYearBonus: null,
    },
    {
      name: "Seo =>  John",
      hireDate: "12-FEB-06",
      job: "Clerk",
      salary: "2700",
      departmentOrUnit: "50",
      endOfYearBonus: "0 => 16%",
    },
    {
      name: "Patel =>  Joshua",
      hireDate: "06-APR-06",
      job: "Clerk",
      salary: "2500",
      departmentOrUnit: "50",
      endOfYearBonus: "16 => 19%",
    },
  ]);
});

Deno.test("should replace multiple texts in multiple columns", async () => {
  const table = sdb.newTable();
  await table.loadData(["test/data/files/employees.csv"]);
  await table.cleanColumnNames();

  await table.replace(["name", "endOfYearBonus"], {
    "%": "",
    ",": ".",
  });

  const data = await table.getData();

  assertEquals(data, [
    {
      name: "OConnell. Donald",
      hireDate: "21-JUN-07",
      job: "Clerk",
      salary: "2600",
      departmentOrUnit: "50",
      endOfYearBonus: "1.94",
    },
    {
      name: "OConnell. Donald",
      hireDate: "21-JUN-07",
      job: "Clerk",
      salary: "2600",
      departmentOrUnit: "50",
      endOfYearBonus: "1.94",
    },
    {
      name: "Grant. Douglas",
      hireDate: "13-JAN-08",
      job: "Clerk",
      salary: "NaN",
      departmentOrUnit: "50",
      endOfYearBonus: "23.39",
    },
    {
      name: null,
      hireDate: "17-SEP-03",
      job: "Assistant",
      salary: "4400",
      departmentOrUnit: "10",
      endOfYearBonus: "17.51",
    },
    {
      name: "Hartstein. Michael",
      hireDate: "17-FEB-04",
      job: "Manager",
      salary: "13000",
      departmentOrUnit: "20",
      endOfYearBonus: "2.71",
    },
    {
      name: "Fay. Pat",
      hireDate: "17-AUG-05",
      job: "Representative",
      salary: "6000",
      departmentOrUnit: "20",
      endOfYearBonus: "18.68",
    },
    {
      name: "Mavris. Susan",
      hireDate: "07-JUN-02",
      job: "Salesperson",
      salary: "6500",
      departmentOrUnit: "40",
      endOfYearBonus: "23.47",
    },
    {
      name: "NaN",
      hireDate: "07-JUN-02",
      job: "Salesperson",
      salary: "10000",
      departmentOrUnit: "xyz",
      endOfYearBonus: "17.63",
    },
    {
      name: "Higgins. Shelley",
      hireDate: "07-JUN-02",
      job: "Manager",
      salary: "12008",
      departmentOrUnit: "110",
      endOfYearBonus: "17.09",
    },
    {
      name: "null",
      hireDate: "07-JUN-02",
      job: "Accountant",
      salary: "8300",
      departmentOrUnit: "110",
      endOfYearBonus: "15.7",
    },
    {
      name: "King. Steven",
      hireDate: null,
      job: "President",
      salary: "24000",
      departmentOrUnit: "90",
      endOfYearBonus: "2.46",
    },
    {
      name: "Kochhar. Neena",
      hireDate: "21-SEP-05",
      job: "Vice-president",
      salary: "&6%",
      departmentOrUnit: "90",
      endOfYearBonus: "11.6",
    },
    {
      name: "De Haan. Lex",
      hireDate: "null",
      job: "Vice-president",
      salary: "17000",
      departmentOrUnit: "90",
      endOfYearBonus: "23.43",
    },
    {
      name: "Hunold. Alexander",
      hireDate: "03-JAN-06",
      job: "Programmer",
      salary: "9000",
      departmentOrUnit: "60",
      endOfYearBonus: "23.01",
    },
    {
      name: "Ernst. Bruce",
      hireDate: "21-MAY-07",
      job: "Programmer",
      salary: "6000",
      departmentOrUnit: "60",
      endOfYearBonus: "25.91",
    },
    {
      name: "Austin. David",
      hireDate: "NaN",
      job: "Programmer",
      salary: "4800",
      departmentOrUnit: "null",
      endOfYearBonus: "6.89",
    },
    {
      name: "Pataballa. Valli",
      hireDate: "abc",
      job: "Programmer",
      salary: null,
      departmentOrUnit: "60",
      endOfYearBonus: "1.62",
    },
    {
      name: "Lorentz. Diana",
      hireDate: "07-ARB-07",
      job: "Programmer",
      salary: "4200",
      departmentOrUnit: "60",
      endOfYearBonus: "13.17",
    },
    {
      name: "Greenberg. Nancy",
      hireDate: "17-AUG-02",
      job: "Manager",
      salary: "12008",
      departmentOrUnit: "100",
      endOfYearBonus: "74.69",
    },
    {
      name: "Faviet. Daniel",
      hireDate: "16-AUG-02",
      job: "Accountant",
      salary: "9000",
      departmentOrUnit: "100",
      endOfYearBonus: "2.92",
    },
    {
      name: "Chen. John",
      hireDate: "28-SEP-05",
      job: "Accountant",
      salary: "8200",
      departmentOrUnit: "100",
      endOfYearBonus: "9.31",
    },
    {
      name: "Sciarra. Ismael",
      hireDate: "30-SEP-05",
      job: "Accountant",
      salary: "7700",
      departmentOrUnit: "100",
      endOfYearBonus: "13.18",
    },
    {
      name: "Urman. Jose Manuel",
      hireDate: "07-MAR-06",
      job: "Accountant",
      salary: "7800",
      departmentOrUnit: "100",
      endOfYearBonus: "1.33",
    },
    {
      name: "Popp. Luis",
      hireDate: "07-DEC-07",
      job: "Accountant",
      salary: "6900",
      departmentOrUnit: "100",
      endOfYearBonus: "2.98",
    },
    {
      name: "Raphaely. Den",
      hireDate: "07-DEC-02",
      job: "Manager",
      salary: "11000",
      departmentOrUnit: "30",
      endOfYearBonus: "3.35",
    },
    {
      name: "Khoo. Alexander",
      hireDate: "18-MAY-03",
      job: "Clerk",
      salary: "3100",
      departmentOrUnit: "30",
      endOfYearBonus: "19.81",
    },
    {
      name: "Baida. Shelli",
      hireDate: "24-DEC-05",
      job: "Clerk",
      salary: "2900",
      departmentOrUnit: "30",
      endOfYearBonus: "11.06",
    },
    {
      name: "Tobias. Sigal",
      hireDate: "24-JUL-05",
      job: "NaN",
      salary: "2800",
      departmentOrUnit: null,
      endOfYearBonus: "undefined",
    },
    {
      name: "Himuro. Guy",
      hireDate: "15-NOV-05",
      job: "Clerk",
      salary: "2600",
      departmentOrUnit: "30",
      endOfYearBonus: "25.98",
    },
    {
      name: "Colmenares. Karen",
      hireDate: "10-AUG-07",
      job: "Clerk",
      salary: "2500",
      departmentOrUnit: "30",
      endOfYearBonus: "15.8",
    },
    {
      name: "Weiss. Matthew",
      hireDate: "18-JUL-04",
      job: "Manager",
      salary: "8000",
      departmentOrUnit: "50",
      endOfYearBonus: "25.17",
    },
    {
      name: "Fripp. Adam",
      hireDate: "10-APR-05",
      job: "Manager",
      salary: "8200",
      departmentOrUnit: "50",
      endOfYearBonus: "21",
    },
    {
      name: "Kaufling. Payam",
      hireDate: "01-MAY-03",
      job: "Manager",
      salary: "7900",
      departmentOrUnit: "undefined",
      endOfYearBonus: "21.33",
    },
    {
      name: "Vollman. Shanta",
      hireDate: "10-OCT-05",
      job: "null",
      salary: "6500",
      departmentOrUnit: "50",
      endOfYearBonus: "3.45",
    },
    {
      name: "Mourgos. Kevin",
      hireDate: "undefined",
      job: "Manager",
      salary: "5800",
      departmentOrUnit: "50",
      endOfYearBonus: "19.07",
    },
    {
      name: "Nayer. Julia",
      hireDate: "16-JUL-05",
      job: "Clerk",
      salary: "3200",
      departmentOrUnit: "50",
      endOfYearBonus: "18.7",
    },
    {
      name: "Mikkilineni. Irene",
      hireDate: "28-SEP-06",
      job: "Clerk",
      salary: "2700",
      departmentOrUnit: "50",
      endOfYearBonus: "11.82",
    },
    {
      name: "Landry. James",
      hireDate: "14-JAN-07",
      job: "Clerk",
      salary: "2400",
      departmentOrUnit: "50",
      endOfYearBonus: "NaN",
    },
    {
      name: "Markle. Steven",
      hireDate: "NaN",
      job: "Clerk",
      salary: "2200",
      departmentOrUnit: "50",
      endOfYearBonus: "11.26",
    },
    {
      name: "Bissot. Laura",
      hireDate: "20-AUG-05",
      job: "undefined",
      salary: "3300",
      departmentOrUnit: "50",
      endOfYearBonus: "4.53",
    },
    {
      name: "Atkinson. Mozhe",
      hireDate: "30-OCT-05",
      job: "Clerk",
      salary: "undefined",
      departmentOrUnit: "50",
      endOfYearBonus: "9.61",
    },
    {
      name: "Marlow. James",
      hireDate: "16-FEB-05",
      job: "Clerk",
      salary: "2500",
      departmentOrUnit: "50",
      endOfYearBonus: "15.74",
    },
    {
      name: "Olson. TJ",
      hireDate: "10-APR-07",
      job: "Clerk",
      salary: "2100",
      departmentOrUnit: "null",
      endOfYearBonus: "22.3",
    },
    {
      name: "undefined",
      hireDate: "14-JUN-04",
      job: "Clerk",
      salary: "3300",
      departmentOrUnit: "50",
      endOfYearBonus: "18.54",
    },
    {
      name: "Rogers. Michael",
      hireDate: "26-AUG-06",
      job: "Clerk",
      salary: "2900",
      departmentOrUnit: "50",
      endOfYearBonus: "null",
    },
    {
      name: "Gee. Ki",
      hireDate: "12-DEC-07",
      job: "NaN",
      salary: "2400",
      departmentOrUnit: "50",
      endOfYearBonus: "12.64",
    },
    {
      name: "Philtanker. Hazel",
      hireDate: "06-FEB-08",
      job: "Clerk",
      salary: "2200",
      departmentOrUnit: "NaN",
      endOfYearBonus: "24.17",
    },
    {
      name: "Ladwig. Renske",
      hireDate: "14-JUL-03",
      job: null,
      salary: "3600",
      departmentOrUnit: "50",
      endOfYearBonus: "17.86",
    },
    {
      name: "Stiles. Stephen",
      hireDate: "26-OCT-05",
      job: "Clerk",
      salary: "3200",
      departmentOrUnit: "50",
      endOfYearBonus: null,
    },
    {
      name: "Seo. John",
      hireDate: "12-FEB-06",
      job: "Clerk",
      salary: "2700",
      departmentOrUnit: "50",
      endOfYearBonus: "0.16",
    },
    {
      name: "Patel. Joshua",
      hireDate: "06-APR-06",
      job: "Clerk",
      salary: "2500",
      departmentOrUnit: "50",
      endOfYearBonus: "16.19",
    },
  ]);
});
Deno.test("should work with ' without throwing an error", async () => {
  const table = sdb.newTable();
  await table.loadData(["test/data/files/employees.csv"]);
  await table.cleanColumnNames();

  await table.replace(["name"], {
    ",": "'",
  });

  const data = await table.getData();

  assertEquals(data, [
    {
      name: "OConnell' Donald",
      hireDate: "21-JUN-07",
      job: "Clerk",
      salary: "2600",
      departmentOrUnit: "50",
      endOfYearBonus: "1,94%",
    },
    {
      name: "OConnell' Donald",
      hireDate: "21-JUN-07",
      job: "Clerk",
      salary: "2600",
      departmentOrUnit: "50",
      endOfYearBonus: "1,94%",
    },
    {
      name: "Grant' Douglas",
      hireDate: "13-JAN-08",
      job: "Clerk",
      salary: "NaN",
      departmentOrUnit: "50",
      endOfYearBonus: "23,39%",
    },
    {
      name: null,
      hireDate: "17-SEP-03",
      job: "Assistant",
      salary: "4400",
      departmentOrUnit: "10",
      endOfYearBonus: "17,51%",
    },
    {
      name: "Hartstein' Michael",
      hireDate: "17-FEB-04",
      job: "Manager",
      salary: "13000",
      departmentOrUnit: "20",
      endOfYearBonus: "2,71%",
    },
    {
      name: "Fay' Pat",
      hireDate: "17-AUG-05",
      job: "Representative",
      salary: "6000",
      departmentOrUnit: "20",
      endOfYearBonus: "18,68%",
    },
    {
      name: "Mavris' Susan",
      hireDate: "07-JUN-02",
      job: "Salesperson",
      salary: "6500",
      departmentOrUnit: "40",
      endOfYearBonus: "23,47%",
    },
    {
      name: "NaN",
      hireDate: "07-JUN-02",
      job: "Salesperson",
      salary: "10000",
      departmentOrUnit: "xyz",
      endOfYearBonus: "17,63%",
    },
    {
      name: "Higgins' Shelley",
      hireDate: "07-JUN-02",
      job: "Manager",
      salary: "12008",
      departmentOrUnit: "110",
      endOfYearBonus: "17,09%",
    },
    {
      name: "null",
      hireDate: "07-JUN-02",
      job: "Accountant",
      salary: "8300",
      departmentOrUnit: "110",
      endOfYearBonus: "15,7%",
    },
    {
      name: "King' Steven",
      hireDate: null,
      job: "President",
      salary: "24000",
      departmentOrUnit: "90",
      endOfYearBonus: "2,46%",
    },
    {
      name: "Kochhar' Neena",
      hireDate: "21-SEP-05",
      job: "Vice-president",
      salary: "&6%",
      departmentOrUnit: "90",
      endOfYearBonus: "11,6%",
    },
    {
      name: "De Haan' Lex",
      hireDate: "null",
      job: "Vice-president",
      salary: "17000",
      departmentOrUnit: "90",
      endOfYearBonus: "23,43%",
    },
    {
      name: "Hunold' Alexander",
      hireDate: "03-JAN-06",
      job: "Programmer",
      salary: "9000",
      departmentOrUnit: "60",
      endOfYearBonus: "23,01%",
    },
    {
      name: "Ernst' Bruce",
      hireDate: "21-MAY-07",
      job: "Programmer",
      salary: "6000",
      departmentOrUnit: "60",
      endOfYearBonus: "25,91%",
    },
    {
      name: "Austin' David",
      hireDate: "NaN",
      job: "Programmer",
      salary: "4800",
      departmentOrUnit: "null",
      endOfYearBonus: "6,89%",
    },
    {
      name: "Pataballa' Valli",
      hireDate: "abc",
      job: "Programmer",
      salary: null,
      departmentOrUnit: "60",
      endOfYearBonus: "1,62%",
    },
    {
      name: "Lorentz' Diana",
      hireDate: "07-ARB-07",
      job: "Programmer",
      salary: "4200",
      departmentOrUnit: "60",
      endOfYearBonus: "13,17%",
    },
    {
      name: "Greenberg' Nancy",
      hireDate: "17-AUG-02",
      job: "Manager",
      salary: "12008",
      departmentOrUnit: "100",
      endOfYearBonus: "74,69%",
    },
    {
      name: "Faviet' Daniel",
      hireDate: "16-AUG-02",
      job: "Accountant",
      salary: "9000",
      departmentOrUnit: "100",
      endOfYearBonus: "2,92%",
    },
    {
      name: "Chen' John",
      hireDate: "28-SEP-05",
      job: "Accountant",
      salary: "8200",
      departmentOrUnit: "100",
      endOfYearBonus: "9,31%",
    },
    {
      name: "Sciarra' Ismael",
      hireDate: "30-SEP-05",
      job: "Accountant",
      salary: "7700",
      departmentOrUnit: "100",
      endOfYearBonus: "13,18%",
    },
    {
      name: "Urman' Jose Manuel",
      hireDate: "07-MAR-06",
      job: "Accountant",
      salary: "7800",
      departmentOrUnit: "100",
      endOfYearBonus: "1,33%",
    },
    {
      name: "Popp' Luis",
      hireDate: "07-DEC-07",
      job: "Accountant",
      salary: "6900",
      departmentOrUnit: "100",
      endOfYearBonus: "2,98%",
    },
    {
      name: "Raphaely' Den",
      hireDate: "07-DEC-02",
      job: "Manager",
      salary: "11000",
      departmentOrUnit: "30",
      endOfYearBonus: "3,35%",
    },
    {
      name: "Khoo' Alexander",
      hireDate: "18-MAY-03",
      job: "Clerk",
      salary: "3100",
      departmentOrUnit: "30",
      endOfYearBonus: "19,81%",
    },
    {
      name: "Baida' Shelli",
      hireDate: "24-DEC-05",
      job: "Clerk",
      salary: "2900",
      departmentOrUnit: "30",
      endOfYearBonus: "11,06%",
    },
    {
      name: "Tobias' Sigal",
      hireDate: "24-JUL-05",
      job: "NaN",
      salary: "2800",
      departmentOrUnit: null,
      endOfYearBonus: "undefined",
    },
    {
      name: "Himuro' Guy",
      hireDate: "15-NOV-05",
      job: "Clerk",
      salary: "2600",
      departmentOrUnit: "30",
      endOfYearBonus: "25,98%",
    },
    {
      name: "Colmenares' Karen",
      hireDate: "10-AUG-07",
      job: "Clerk",
      salary: "2500",
      departmentOrUnit: "30",
      endOfYearBonus: "15,8%",
    },
    {
      name: "Weiss' Matthew",
      hireDate: "18-JUL-04",
      job: "Manager",
      salary: "8000",
      departmentOrUnit: "50",
      endOfYearBonus: "25,17%",
    },
    {
      name: "Fripp' Adam",
      hireDate: "10-APR-05",
      job: "Manager",
      salary: "8200",
      departmentOrUnit: "50",
      endOfYearBonus: "21%",
    },
    {
      name: "Kaufling' Payam",
      hireDate: "01-MAY-03",
      job: "Manager",
      salary: "7900",
      departmentOrUnit: "undefined",
      endOfYearBonus: "21,33%",
    },
    {
      name: "Vollman' Shanta",
      hireDate: "10-OCT-05",
      job: "null",
      salary: "6500",
      departmentOrUnit: "50",
      endOfYearBonus: "3,45%",
    },
    {
      name: "Mourgos' Kevin",
      hireDate: "undefined",
      job: "Manager",
      salary: "5800",
      departmentOrUnit: "50",
      endOfYearBonus: "19,07%",
    },
    {
      name: "Nayer' Julia",
      hireDate: "16-JUL-05",
      job: "Clerk",
      salary: "3200",
      departmentOrUnit: "50",
      endOfYearBonus: "18,7%",
    },
    {
      name: "Mikkilineni' Irene",
      hireDate: "28-SEP-06",
      job: "Clerk",
      salary: "2700",
      departmentOrUnit: "50",
      endOfYearBonus: "11,82%",
    },
    {
      name: "Landry' James",
      hireDate: "14-JAN-07",
      job: "Clerk",
      salary: "2400",
      departmentOrUnit: "50",
      endOfYearBonus: "NaN",
    },
    {
      name: "Markle' Steven",
      hireDate: "NaN",
      job: "Clerk",
      salary: "2200",
      departmentOrUnit: "50",
      endOfYearBonus: "11,26%",
    },
    {
      name: "Bissot' Laura",
      hireDate: "20-AUG-05",
      job: "undefined",
      salary: "3300",
      departmentOrUnit: "50",
      endOfYearBonus: "4,53%",
    },
    {
      name: "Atkinson' Mozhe",
      hireDate: "30-OCT-05",
      job: "Clerk",
      salary: "undefined",
      departmentOrUnit: "50",
      endOfYearBonus: "9,61%",
    },
    {
      name: "Marlow' James",
      hireDate: "16-FEB-05",
      job: "Clerk",
      salary: "2500",
      departmentOrUnit: "50",
      endOfYearBonus: "15,74%",
    },
    {
      name: "Olson' TJ",
      hireDate: "10-APR-07",
      job: "Clerk",
      salary: "2100",
      departmentOrUnit: "null",
      endOfYearBonus: "22,3%",
    },
    {
      name: "undefined",
      hireDate: "14-JUN-04",
      job: "Clerk",
      salary: "3300",
      departmentOrUnit: "50",
      endOfYearBonus: "18,54%",
    },
    {
      name: "Rogers' Michael",
      hireDate: "26-AUG-06",
      job: "Clerk",
      salary: "2900",
      departmentOrUnit: "50",
      endOfYearBonus: "null",
    },
    {
      name: "Gee' Ki",
      hireDate: "12-DEC-07",
      job: "NaN",
      salary: "2400",
      departmentOrUnit: "50",
      endOfYearBonus: "12,64%",
    },
    {
      name: "Philtanker' Hazel",
      hireDate: "06-FEB-08",
      job: "Clerk",
      salary: "2200",
      departmentOrUnit: "NaN",
      endOfYearBonus: "24,17%",
    },
    {
      name: "Ladwig' Renske",
      hireDate: "14-JUL-03",
      job: null,
      salary: "3600",
      departmentOrUnit: "50",
      endOfYearBonus: "17,86%",
    },
    {
      name: "Stiles' Stephen",
      hireDate: "26-OCT-05",
      job: "Clerk",
      salary: "3200",
      departmentOrUnit: "50",
      endOfYearBonus: null,
    },
    {
      name: "Seo' John",
      hireDate: "12-FEB-06",
      job: "Clerk",
      salary: "2700",
      departmentOrUnit: "50",
      endOfYearBonus: "0,16%",
    },
    {
      name: "Patel' Joshua",
      hireDate: "06-APR-06",
      job: "Clerk",
      salary: "2500",
      departmentOrUnit: "50",
      endOfYearBonus: "16,19%",
    },
  ]);
});
Deno.test("should use a regular expression", async () => {
  const table = sdb.newTable();
  await table.loadData(["test/data/files/employees.csv"]);
  await table.cleanColumnNames();

  await table.replace("hireDate", { "\\d+": "-" }, { regex: true });

  const data = await table.getData();

  assertEquals(data, [
    {
      name: "OConnell, Donald",
      hireDate: "--JUN--",
      job: "Clerk",
      salary: "2600",
      departmentOrUnit: "50",
      endOfYearBonus: "1,94%",
    },
    {
      name: "OConnell, Donald",
      hireDate: "--JUN--",
      job: "Clerk",
      salary: "2600",
      departmentOrUnit: "50",
      endOfYearBonus: "1,94%",
    },
    {
      name: "Grant, Douglas",
      hireDate: "--JAN--",
      job: "Clerk",
      salary: "NaN",
      departmentOrUnit: "50",
      endOfYearBonus: "23,39%",
    },
    {
      name: null,
      hireDate: "--SEP--",
      job: "Assistant",
      salary: "4400",
      departmentOrUnit: "10",
      endOfYearBonus: "17,51%",
    },
    {
      name: "Hartstein, Michael",
      hireDate: "--FEB--",
      job: "Manager",
      salary: "13000",
      departmentOrUnit: "20",
      endOfYearBonus: "2,71%",
    },
    {
      name: "Fay, Pat",
      hireDate: "--AUG--",
      job: "Representative",
      salary: "6000",
      departmentOrUnit: "20",
      endOfYearBonus: "18,68%",
    },
    {
      name: "Mavris, Susan",
      hireDate: "--JUN--",
      job: "Salesperson",
      salary: "6500",
      departmentOrUnit: "40",
      endOfYearBonus: "23,47%",
    },
    {
      name: "NaN",
      hireDate: "--JUN--",
      job: "Salesperson",
      salary: "10000",
      departmentOrUnit: "xyz",
      endOfYearBonus: "17,63%",
    },
    {
      name: "Higgins, Shelley",
      hireDate: "--JUN--",
      job: "Manager",
      salary: "12008",
      departmentOrUnit: "110",
      endOfYearBonus: "17,09%",
    },
    {
      name: "null",
      hireDate: "--JUN--",
      job: "Accountant",
      salary: "8300",
      departmentOrUnit: "110",
      endOfYearBonus: "15,7%",
    },
    {
      name: "King, Steven",
      hireDate: null,
      job: "President",
      salary: "24000",
      departmentOrUnit: "90",
      endOfYearBonus: "2,46%",
    },
    {
      name: "Kochhar, Neena",
      hireDate: "--SEP--",
      job: "Vice-president",
      salary: "&6%",
      departmentOrUnit: "90",
      endOfYearBonus: "11,6%",
    },
    {
      name: "De Haan, Lex",
      hireDate: "null",
      job: "Vice-president",
      salary: "17000",
      departmentOrUnit: "90",
      endOfYearBonus: "23,43%",
    },
    {
      name: "Hunold, Alexander",
      hireDate: "--JAN--",
      job: "Programmer",
      salary: "9000",
      departmentOrUnit: "60",
      endOfYearBonus: "23,01%",
    },
    {
      name: "Ernst, Bruce",
      hireDate: "--MAY--",
      job: "Programmer",
      salary: "6000",
      departmentOrUnit: "60",
      endOfYearBonus: "25,91%",
    },
    {
      name: "Austin, David",
      hireDate: "NaN",
      job: "Programmer",
      salary: "4800",
      departmentOrUnit: "null",
      endOfYearBonus: "6,89%",
    },
    {
      name: "Pataballa, Valli",
      hireDate: "abc",
      job: "Programmer",
      salary: null,
      departmentOrUnit: "60",
      endOfYearBonus: "1,62%",
    },
    {
      name: "Lorentz, Diana",
      hireDate: "--ARB--",
      job: "Programmer",
      salary: "4200",
      departmentOrUnit: "60",
      endOfYearBonus: "13,17%",
    },
    {
      name: "Greenberg, Nancy",
      hireDate: "--AUG--",
      job: "Manager",
      salary: "12008",
      departmentOrUnit: "100",
      endOfYearBonus: "74,69%",
    },
    {
      name: "Faviet, Daniel",
      hireDate: "--AUG--",
      job: "Accountant",
      salary: "9000",
      departmentOrUnit: "100",
      endOfYearBonus: "2,92%",
    },
    {
      name: "Chen, John",
      hireDate: "--SEP--",
      job: "Accountant",
      salary: "8200",
      departmentOrUnit: "100",
      endOfYearBonus: "9,31%",
    },
    {
      name: "Sciarra, Ismael",
      hireDate: "--SEP--",
      job: "Accountant",
      salary: "7700",
      departmentOrUnit: "100",
      endOfYearBonus: "13,18%",
    },
    {
      name: "Urman, Jose Manuel",
      hireDate: "--MAR--",
      job: "Accountant",
      salary: "7800",
      departmentOrUnit: "100",
      endOfYearBonus: "1,33%",
    },
    {
      name: "Popp, Luis",
      hireDate: "--DEC--",
      job: "Accountant",
      salary: "6900",
      departmentOrUnit: "100",
      endOfYearBonus: "2,98%",
    },
    {
      name: "Raphaely, Den",
      hireDate: "--DEC--",
      job: "Manager",
      salary: "11000",
      departmentOrUnit: "30",
      endOfYearBonus: "3,35%",
    },
    {
      name: "Khoo, Alexander",
      hireDate: "--MAY--",
      job: "Clerk",
      salary: "3100",
      departmentOrUnit: "30",
      endOfYearBonus: "19,81%",
    },
    {
      name: "Baida, Shelli",
      hireDate: "--DEC--",
      job: "Clerk",
      salary: "2900",
      departmentOrUnit: "30",
      endOfYearBonus: "11,06%",
    },
    {
      name: "Tobias, Sigal",
      hireDate: "--JUL--",
      job: "NaN",
      salary: "2800",
      departmentOrUnit: null,
      endOfYearBonus: "undefined",
    },
    {
      name: "Himuro, Guy",
      hireDate: "--NOV--",
      job: "Clerk",
      salary: "2600",
      departmentOrUnit: "30",
      endOfYearBonus: "25,98%",
    },
    {
      name: "Colmenares, Karen",
      hireDate: "--AUG--",
      job: "Clerk",
      salary: "2500",
      departmentOrUnit: "30",
      endOfYearBonus: "15,8%",
    },
    {
      name: "Weiss, Matthew",
      hireDate: "--JUL--",
      job: "Manager",
      salary: "8000",
      departmentOrUnit: "50",
      endOfYearBonus: "25,17%",
    },
    {
      name: "Fripp, Adam",
      hireDate: "--APR--",
      job: "Manager",
      salary: "8200",
      departmentOrUnit: "50",
      endOfYearBonus: "21%",
    },
    {
      name: "Kaufling, Payam",
      hireDate: "--MAY--",
      job: "Manager",
      salary: "7900",
      departmentOrUnit: "undefined",
      endOfYearBonus: "21,33%",
    },
    {
      name: "Vollman, Shanta",
      hireDate: "--OCT--",
      job: "null",
      salary: "6500",
      departmentOrUnit: "50",
      endOfYearBonus: "3,45%",
    },
    {
      name: "Mourgos, Kevin",
      hireDate: "undefined",
      job: "Manager",
      salary: "5800",
      departmentOrUnit: "50",
      endOfYearBonus: "19,07%",
    },
    {
      name: "Nayer, Julia",
      hireDate: "--JUL--",
      job: "Clerk",
      salary: "3200",
      departmentOrUnit: "50",
      endOfYearBonus: "18,7%",
    },
    {
      name: "Mikkilineni, Irene",
      hireDate: "--SEP--",
      job: "Clerk",
      salary: "2700",
      departmentOrUnit: "50",
      endOfYearBonus: "11,82%",
    },
    {
      name: "Landry, James",
      hireDate: "--JAN--",
      job: "Clerk",
      salary: "2400",
      departmentOrUnit: "50",
      endOfYearBonus: "NaN",
    },
    {
      name: "Markle, Steven",
      hireDate: "NaN",
      job: "Clerk",
      salary: "2200",
      departmentOrUnit: "50",
      endOfYearBonus: "11,26%",
    },
    {
      name: "Bissot, Laura",
      hireDate: "--AUG--",
      job: "undefined",
      salary: "3300",
      departmentOrUnit: "50",
      endOfYearBonus: "4,53%",
    },
    {
      name: "Atkinson, Mozhe",
      hireDate: "--OCT--",
      job: "Clerk",
      salary: "undefined",
      departmentOrUnit: "50",
      endOfYearBonus: "9,61%",
    },
    {
      name: "Marlow, James",
      hireDate: "--FEB--",
      job: "Clerk",
      salary: "2500",
      departmentOrUnit: "50",
      endOfYearBonus: "15,74%",
    },
    {
      name: "Olson, TJ",
      hireDate: "--APR--",
      job: "Clerk",
      salary: "2100",
      departmentOrUnit: "null",
      endOfYearBonus: "22,3%",
    },
    {
      name: "undefined",
      hireDate: "--JUN--",
      job: "Clerk",
      salary: "3300",
      departmentOrUnit: "50",
      endOfYearBonus: "18,54%",
    },
    {
      name: "Rogers, Michael",
      hireDate: "--AUG--",
      job: "Clerk",
      salary: "2900",
      departmentOrUnit: "50",
      endOfYearBonus: "null",
    },
    {
      name: "Gee, Ki",
      hireDate: "--DEC--",
      job: "NaN",
      salary: "2400",
      departmentOrUnit: "50",
      endOfYearBonus: "12,64%",
    },
    {
      name: "Philtanker, Hazel",
      hireDate: "--FEB--",
      job: "Clerk",
      salary: "2200",
      departmentOrUnit: "NaN",
      endOfYearBonus: "24,17%",
    },
    {
      name: "Ladwig, Renske",
      hireDate: "--JUL--",
      job: null,
      salary: "3600",
      departmentOrUnit: "50",
      endOfYearBonus: "17,86%",
    },
    {
      name: "Stiles, Stephen",
      hireDate: "--OCT--",
      job: "Clerk",
      salary: "3200",
      departmentOrUnit: "50",
      endOfYearBonus: null,
    },
    {
      name: "Seo, John",
      hireDate: "--FEB--",
      job: "Clerk",
      salary: "2700",
      departmentOrUnit: "50",
      endOfYearBonus: "0,16%",
    },
    {
      name: "Patel, Joshua",
      hireDate: "--APR--",
      job: "Clerk",
      salary: "2500",
      departmentOrUnit: "50",
      endOfYearBonus: "16,19%",
    },
  ]);
});

await sdb.done();
