import assert from "assert"
import { SimpleDataNode } from "../../../../src/index.js"

describe("loadDataFromHtmlTable", function () {
    it("should return an array of objects from the nth table in a webpage", async function () {
        const sd = await new SimpleDataNode().loadDataFromHtmlTable({
            url: "https://en.wikipedia.org/wiki/Medieval_demography",
            tableNumber: 3,
        })

        assert.deepStrictEqual(sd.getData(), [
            { Year: "1000" },
            { "Total European population,millions": "56.4" },
            { "Absolute growth per period,millions": "—" },
            { "Average growth per year,thousands": "—" },
            { "Absolute growth per century,%": "—" },
            { "Average growth per year,%": "—" },
            { Year: "1100" },
            { "Total European population,millions": "62.1" },
            { "Absolute growth per period,millions": "5.7" },
            { "Average growth per year,thousands": "57" },
            { "Absolute growth per century,%": "10.1" },
            { "Average growth per year,%": "0.10" },
            { Year: "1200" },
            { "Total European population,millions": "68.0" },
            { "Absolute growth per period,millions": "5.9" },
            { "Average growth per year,thousands": "59" },
            { "Absolute growth per century,%": "9.5" },
            { "Average growth per year,%": "0.09" },
            { Year: "1250" },
            { "Total European population,millions": "72.9" },
            { "Absolute growth per period,millions": "4.9" },
            { "Average growth per year,thousands": "98" },
            { "Absolute growth per century,%": "15.7" },
            { "Average growth per year,%": "0.14" },
            { Year: "1300" },
            { "Total European population,millions": "78.7" },
            { "Absolute growth per period,millions": "5.8" },
            { "Average growth per year,thousands": "116" },
            { "Absolute growth per century,%": "0.15" },
            { Year: "1350" },
            { "Total European population,millions": "70.7" },
            { "Absolute growth per period,millions": "−8.0" },
            { "Average growth per year,thousands": "−160" },
            { "Absolute growth per century,%": "−0.8" },
            { "Average growth per year,%": "−0.21" },
            { Year: "1400" },
            { "Total European population,millions": "78.1" },
            { "Absolute growth per period,millions": "7.4" },
            { "Average growth per year,thousands": "148" },
            { "Absolute growth per century,%": "0.20" },
            { Year: "1450" },
            { "Total European population,millions": "83.0" },
            { "Absolute growth per period,millions": "4.9" },
            { "Average growth per year,thousands": "98" },
            { "Absolute growth per century,%": "16.1" },
            { "Average growth per year,%": "0.12" },
            { Year: "1500" },
            { "Total European population,millions": "90.7" },
            { "Absolute growth per period,millions": "7.7" },
            { "Average growth per year,thousands": "154" },
            { "Absolute growth per century,%": "0.18" },
        ])
    })
})
