name: SDA CLI

on:
  pull_request:
    branches: [main]

jobs:
  all-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno task all-tests
