name: SDA CLI

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        env:
          GH_TOKEN: ${{ github.token }}
          tag: ${{ github.ref_name }}
        run: echo "Environment variables set"
      - name: Create GitHub release
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${tag#v}" \
              --generate-notes
